### ISSUE TITLE
unmounted block device file is deleted/re-created continuously in some runners

### ISSUE THREAD

**Issue by satoru-takeuchi** [actions/runner#1024]
**Describe the bug**

Unmounted block device file is deleted/re-created cotinuously. This behavior happens deterministically in some runners, but never happen in other runners.

[Rook](https://github.com/rook/rook) uses scratch block device in CI. For this purpose, Rook's CI umounts "/mnt", wipes the filesystem information in the corresponding bdev, changes the bdev's owner, and re-uses it as a raw bdev later. We detected that owner information was reset (more preciously, bdev file is re-created) between changing owner and re-using the bdev.

If this problem happens, the following logs are recorded in `dmesg`. Here sdb1 is corresponding to a ext4 filesystem which was mounted in "/mnt".

```console
dmesg
....
[ 1116.905811] docker0: port 4(veth40b3653) entered blocking state
[ 1116.905812] docker0: port 4(veth40b3653) entered forwarding state
[ 1119.483639]  sdb: sdb1
[ 1119.984324]  sdb: sdb1
[ 1124.583154]  sdb: sdb1
[ 1125.103205]  sdb: sdb1
[ 1129.676603]  sdb: sdb1
[ 1130.102950]  sdb: sdb1
[ 1134.776521]  sdb: sdb1
[ 1135.250131]  sdb: sdb1
[ 1139.854729]  sdb: sdb1
[ 1140.258897]  sdb: sdb1
[ 1144.942330]  sdb: sdb1
[ 1145.402839]  sdb: sdb1
[ 1150.033066]  sdb: sdb1
[ 1150.434360]  sdb: sdb1
[ 1155.138325]  sdb: sdb1
[ 1155.701090]  sdb: sdb1
[ 1160.217446]  sdb: sdb1
[ 1160.614816]  sdb: sdb1
[ 1165.293167]  sdb: sdb1
[ 1165.700072]  sdb: sdb1
[ 1170.359880]  sdb: sdb1
[ 1170.746992]  sdb: sdb1
...
```

In this case, even though I changed owner by hand, this file is re-created soon.

```console
$ stat /dev/sdb1
  File: /dev/sdb1
  Size: 0               Blocks: 0          IO Block: 4096   block special file
Device: 6h/6d   Inode: 158         Links: 1     Device type: 8,11
Access: (0660/brw-rw----)  Uid: (    0/    root)   Gid: (    6/    disk)
Access: 2021-03-15 10:06:43.799616689 +0000
Modify: 2021-03-15 10:06:42.351450600 +0000
Change: 2021-03-15 10:06:42.351450600 +0000
 Birth: -
$ sudo chown 167:167 /dev/sdb1 && stat /dev/sdb1
  File: /dev/sdb1
  Size: 0               Blocks: 0          IO Block: 4096   block special file
Device: 6h/6d   Inode: 158         Links: 1     Device type: 8,11
Access: (0660/brw-rw----)  Uid: (  167/ UNKNOWN)   Gid: (  167/ UNKNOWN)
Access: 2021-03-15 10:06:52.516611105 +0000
Modify: 2021-03-15 10:06:52.516611105 +0000
Change: 2021-03-15 10:06:53.012667437 +0000
 Birth: -
$ stat /dev/sdb1
  File: /dev/sdb1
  Size: 0               Blocks: 0          IO Block: 4096   block special file
Device: 6h/6d   Inode: 158         Links: 1     Device type: 8,11
Access: (0660/brw-rw----)  Uid: (  167/ UNKNOWN)   Gid: (  167/ UNKNOWN)
Access: 2021-03-15 10:06:53.896767732 +0000
Modify: 2021-03-15 10:06:52.516611105 +0000
Change: 2021-03-15 10:06:53.012667437 +0000
 Birth: -
$ stat /dev/sdb1
  File: /dev/sdb1
  Size: 0               Blocks: 0          IO Block: 4096   block special file
Device: 6h/6d   Inode: 158         Links: 1     Device type: 8,11
Access: (0660/brw-rw----)  Uid: (    0/    root)   Gid: (    6/    disk)
Access: 2021-03-15 10:06:57.261148573 +0000
Modify: 2021-03-15 10:06:57.261148573 +0000
Change: 2021-03-15 10:06:57.261148573 +0000
 Birth: -
```

As a result of investigation, I found that this behavior seems not to happen if the bdev is mounted or opened.

Related issues:
https://github.com/rook/rook/pull/7404
https://github.com/rook/rook/issues/7405
https://github.com/rook/rook/pull/7467

**To Reproduce**

1. Launch a runner
2. Umount "/mnt" and wipe the corresponding bdev (wiping might not be necessary).
3. Wait for a while

**Expected behavior**

bdev file doesn't flap.

## Runner Version and Platform

Ubuntu 18.04

## What's not working?

After wiping bdev (or umount might be enough to cause this problem, but i'm not sure), bdev is detached/atacched continuously.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by BlaineEXE** [comment]
In reply to @hross 
> The runner doesn't own or create this file. This appears like it might be an issue with your script. If you believe this is being closed in error can you point out who/what is creating this file from the runner?

The file @satoru-takeuchi mentioned is a block device's partition, `/dev/sdb1` (or sometimes `/dev/sda1`) which corresponds to the additional 14G disk added to GH action runners. I don't believe it's correct to say that the runner doesn't own or create the file since it exists directly because of the Azure virtual machine created for running actions. Said partition has a filesystem created on it that is mounted into `/mnt` which also exists because it is part of the virtual machine's startup config.

-----

After some time debugging further issues in Rook, I got some more information about this issue. I am including this analysis for anyone who may be helped by understanding the root cause. I believe the root cause is the same as explained in this article: https://access.redhat.com/solutions/1465913

For us, whenever we would issue `udevadm info --query=property` for the extra disk (`/dev/sdb` in Satoru's initial description) on the GH Action Azure nodes (tested on Ubuntu 18.04), `udev` reloads the partition even though nothing was written to the disk. This causes race conditions with our tests that use the partition for storage. The partition is offline for a period of time while it is being reloaded. 

Adding a udev rule at the end of the chain with the `nowatch` option is currently resolving the issue for Rook.

I don't think that the current behavior can be said to be good or bad since some users may want automatic udev reloading, and others (like Rook's integration tests) may not want it. 

The two azure-specific udev rules created on the system do not have a `watch` option set, so I believe the current behavior is enabled due to configurations in the Ubuntu image being used (see cat of the files below)

```console
$ cat /etc/udev/rules.d/66-azure-storage.rules 
ACTION=="add|change", SUBSYSTEM=="block", ENV{ID_VENDOR}=="Msft", ENV{ID_MODEL}=="Virtual_Disk", GOTO="azure_disk"
GOTO="azure_end"

LABEL="azure_disk"
# Root has a GUID of 0000 as the second value
# The resource/resource has GUID of 0001 as the second value
ATTRS{device_id}=="?00000000-0000-*", ENV{fabric_name}="root", GOTO="azure_names"
ATTRS{device_id}=="?00000000-0001-*", ENV{fabric_name}="resource", GOTO="azure_names"
ATTRS{device_id}=="?00000001-0001-*", ENV{fabric_name}="BEK", GOTO="azure_names"
# Wellknown SCSI controllers
ATTRS{device_id}=="{f8b3781a-1e82-4818-a1c3-63d806ec15bb}", ENV{fabric_scsi_controller}="scsi0", GOTO="azure_datadisk"
ATTRS{device_id}=="{f8b3781b-1e82-4818-a1c3-63d806ec15bb}", ENV{fabric_scsi_controller}="scsi1", GOTO="azure_datadisk"
ATTRS{device_id}=="{f8b3781c-1e82-4818-a1c3-63d806ec15bb}", ENV{fabric_scsi_controller}="scsi2", GOTO="azure_datadisk"
ATTRS{device_id}=="{f8b3781d-1e82-4818-a1c3-63d806ec15bb}", ENV{fabric_scsi_controller}="scsi3", GOTO="azure_datadisk"
GOTO="azure_end"

# Retrieve LUN number for datadisks
LABEL="azure_datadisk"
ENV{DEVTYPE}=="partition", PROGRAM="/bin/sh -c 'readlink /sys/class/block/%k/../device|cut -d: -f4'", ENV{fabric_name}="$env{fabric_scsi_controller}/lun$result", GOTO="azure_names"
PROGRAM="/bin/sh -c 'readlink /sys/class/block/%k/device|cut -d: -f4'", ENV{fabric_name}="$env{fabric_scsi_controller}/lun$result", GOTO="azure_names"
GOTO="azure_end"

# Create the symlinks
LABEL="azure_names"
ENV{DEVTYPE}=="disk", SYMLINK+="disk/azure/$env{fabric_name}"
ENV{DEVTYPE}=="partition", SYMLINK+="disk/azure/$env{fabric_name}-part%n"

LABEL="azure_end"

$ cat /etc/udev/rules.d/99-azure-product-uuid.rules 
SUBSYSTEM!="dmi", GOTO="product_uuid-exit"
ATTR{sys_vendor}!="Microsoft Corporation", GOTO="product_uuid-exit"
ATTR{product_name}!="Virtual Machine", GOTO="product_uuid-exit"
TEST!="/sys/devices/virtual/dmi/id/product_uuid", GOTO="product_uuid-exit"

RUN+="/bin/chmod 0444 /sys/devices/virtual/dmi/id/product_uuid"

LABEL="product_uuid-exit"
```
