### ISSUE TITLE
watch started vs starred

### ISSUE THREAD

**Issue by abitrolly** [actions/runner#1044]
https://docs.github.com/en/actions/reference/events-that-trigger-workflows#watch

> For example, you can run a workflow when someone stars a repository, which is the started activity type that triggers the watch event.
>
> ```
> on:
>   watch:
>     types: [started]
> ```
> 

**Expected behavior**
```
on:
  watch:
    types: [starred]
```

**Comment by hross** [comment]
The reason this is called `started` and not `starred` is a function of how "starred" works at github (not specific to actions or the runner). [See the docs for the webhook event here](https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#watch). In order to keep consistency with the webhook and API behavior we wouldn't change this in actions.
