### ISSUE TITLE
Allow users to select runners with AVX512 support

### ISSUE THREAD

**Issue by 95-martin-orion** [actions/runner#1069]
**Feature description:**
A flag for Github Actions workflows that controls the machine type used in a given run. At a minimum, this would need to differentiate between machines which support AVX512 and those that do not.

**Motivation:**
[Github Actions runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#cloud-hosts-for-github-hosted-runners) use [Dv2 and DSv2](https://docs.microsoft.com/en-us/azure/virtual-machines/dv2-dsv2-series) machines. Some these support AVX512 and some do not. For code which explicitly depends on AVX512 instructions, being able to request AVX512 support would enable consistent behavior in CI tests.

The motivating force behind this request is [qsim for AVX512](https://github.com/quantumlib/qsim/pull/322), which AFAIK is not currently possible to test with Github Actions.

**Comment by TingluoHuang** [comment]
@95-martin-orion GitHub Actions currently only runs on DS2V2 Azure VM which doesn't support AVX512, you will need to set up a self-hosted runner on the hardware you want to test for this.

You can submit a feature request to https://github.community/c/code-to-cloud/github-actions/41 for this since this is a generic request for GitHub actions not for the actions runner itself.

**Comment by mtl1979** [comment]
For reference, https://github.com/orgs/community/discussions/183550
