### ISSUE TITLE
Composite actions steps logs should be clearly separated

### ISSUE THREAD

**Issue by Sytten** [actions/runner#1311]
**Describe the enhancement**
Currently when using composite actions, the logs are all aggregated as if it was one big action.
This becomes quickly problematic to debug an error occurring in one step since we can't easily see when one step starts and one ends.

The best would be to have the "sub-steps" clearly displayed in the interface liked the steps are for a "normal" actions. We could settle for a text based split but it would not be ideal.

I feel this will be essential for `if` conditions to be introduced (issue https://github.com/actions/runner/issues/834), otherwise it will be a mess to try to debug which steps ran and which were skipped.

**Additional information**
Here is what it could look like:
![sub-steps](https://user-images.githubusercontent.com/2366731/132258346-deaba1f2-2b8e-49ef-83c3-b98c9bf89533.png)

**Comment by ethomson** [comment]
Hi!  This seems like a possibly useful addition.  However, suggestions for GitHub Actions functionality belong in the [GitHub feedback forum](https://github.com/github/feedback/discussions/categories/actions-and-packages-feedback), where the product managers and engineers will be able to review them.  This repository is really only focused on the runner application, which is a very small component of GitHub Actions.  If you could open this issue there, that would be very helpful for us!  😄

In the meantime, I'm closing this issue here.  Thanks again!

**Comment by Sytten** [comment]
The issue #834 was clearly a suggestion/feature request. I dont see why it was not closed as such. GitHub issues are clearly better for discoverability than the forums but I will open and backlink here.

**Comment by ethomson** [comment]
Thanks!

**Comment by Sytten** [comment]
This is the discussion: https://github.com/github-community/community/discussions/21276
Please vote on it if you find that important!

**Comment by dvins** [comment]
> This is the discussion: [community/community#21276](https://github.com/orgs/community/discussions/21276) Please vote on it if you find that important!

We have, between this issue and the discussion ticket we're heading into four years! It's one of the top GitHub Action feature requests,  seemingly simpler to implement compared to subfolders, parallel steps, etc.
