### ISSUE TITLE
Support Isolated Actions Inside of JavaScript worksapces

### ISSUE THREAD

**Issue by bnb** [actions/runner#1346]
Thank you 🙇‍♀ for wanting to create a feature in this repository. Before you do, please ensure you are filing the issue in the right place. Issues should only be opened on if the issue **relates to code in this repository**.  

* If you have found a security issue [please submit it here](https://hackerone.com/github)
* If you have questions or issues with the service, writing workflows or actions, then please [visit the GitHub Community Forum's Actions Board](https://github.community/t5/GitHub-Actions/bd-p/actions)
* If you are having an issue or question about GitHub Actions then please [contact customer support](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/about-github-actions#contacting-support)

If you have a feature request that is relevant to this repository, the runner, then please include the information below:

**Describe the enhancement**
npm supports [workspaces](https://docs.npmjs.com/cli/v7/using-npm/workspaces), which is a feature that enables monorepos of packages to be managed by npm. This is a pattern that's been adopted across the JavaScript ecosystem via other tools, like Yarn workspaces, Lerna workspaces, and others.

It would be extremely useful if I could have a `.github` in a subdirectory (a.k.a. a child workspace) and have *only* that action run on whatever conditions would trigger it.

I'm not sure if "just put a `.github` folder in a subdirectory" is enough, or if there'd need to be more _enhanced_ interaction.

**Comment by ethomson** [comment]
Hi!  This seems like a possibly useful addition.  However, suggestions for GitHub Actions functionality belong in the [GitHub feedback forum](https://github.com/github/feedback/discussions/categories/actions-and-packages-feedback), where the product managers and engineers will be able to review them.  This repository is really only focused on the runner application, which is a very small component of GitHub Actions.  If you could open this issue there, that would be very helpful for us!  😄

In the meantime, I'm closing this issue here.  Thanks again!
