### ISSUE TITLE
Add additional informtions for error message which misses uses/run

### ISSUE THREAD

**Issue by Fettpet** [actions/runner#1480]
**Describe the enhancement**
I ran into the error message "Error : .github#L1 every step must define a `uses` or `run` key". The error message misses the step which hasn't a 'uses' or 'run' key.  The debugging process would easier if the message contains the line number and/or the name of the step which suffers of a uses/run key.

**Code Snippet**
For example these code snippet is wrong. It is hard to see, that the problem is the additional '-' by uses.
```
      - name: Checkout source
      - uses: actions/checkout@v2
```

**Comment by ethomson** [comment]
Hi @Fettpet, this seems like a possibly useful addition.  However, suggestions for GitHub Actions functionality belong in the [GitHub feedback forum](https://github.com/github/feedback/discussions/categories/actions-and-packages-feedback), where the product managers and engineers will be able to review them.  This repository is really only focused on the runner application, which is a very small component of GitHub Actions.  If you could open this issue there, that would be very helpful for us!  😄

In the meantime, I'm closing this issue here.  Thanks again!

**Comment by ethomson** [comment]
Thanks!
