### ISSUE TITLE
Allow Workflow Templates to be placed inside a folder .github/workflows/templates

### ISSUE THREAD

**Issue by AllanOricil** [actions/runner#1509]
**Describe the enhancement**
At the moment workflow templates must be placed at .github/workflows

![Screenshot 2021-11-25 at 13 47 44](https://user-images.githubusercontent.com/55927613/143478674-f403cda3-c4a1-47af-ad41-abbabb053ac4.png)

When I tried something like the image below, I got an error message saying something like: 

'Workflows have to be inside .github/workflows ... top-level' 

![Screenshot 2021-11-25 at 13 48 12](https://user-images.githubusercontent.com/55927613/143478723-f7b898e7-978a-4805-9b85-2e68c11ea31b.png)

Enabling developers to add their templates in a subfolder makes things organized. 

**Code Snippet**
N/A

**Additional information**
N/A

NOTE: if the feature request has been agreed upon then the assignee will create an ADR.   See docs/adrs/README.md

**Comment by ethomson** [comment]
Hi @AllanOricil, this seems like a possibly useful addition.  However, suggestions for GitHub Actions functionality belong in the [GitHub feedback forum](https://github.com/github/feedback/discussions/categories/actions-and-packages-feedback), where the product managers and engineers will be able to review them.  This repository is really only focused on the runner application, which is a very small component of GitHub Actions.  If you could open this issue there, that would be very helpful for us!  😄

In the meantime, I'm closing this issue here.  Thanks again!
