### ISSUE TITLE
Provide staged rollout progress in the readme

### ISSUE THREAD

**Issue by Cyberbeni** [actions/runner#1524]
**Describe the enhancement**

The virtual-environments repository has staged rollout progress displayed in the readme: https://github.com/actions/virtual-environments#available-environments

As I didn't see anything like this, I updated my action to use node16 and it ran fine for me, so I made a new release and updated the v2 branch to point to this release but after a couple minutes, I had an open issue about my action failing due to node16 not being recognized by the runner.

https://github.com/Cyberbeni/install-swift-tool/issues/113

**Comment by TingluoHuang** [comment]
You better bump the major version of your actions when consuming node16 as runtime, since it's a breaking change for people using old version runner in enterprise server (GHES).
@ethomson FYI about the changelog.

**Comment by ethomson** [comment]
Thanks for the suggestion.  We would prefer you to watch the [GitHub changelog](https://github.blog/changelog) which is where we'll communicate these sorts of things.  That's because we may have everything rolled out to the rings but other pieces may not be ready.  Right now, we've got node16 in the runner, but we're waiting until a few other unrelated changes land before we want to start encouraging you to use it.  Keep an eye one the changelog!  👀
