### ISSUE TITLE
Task list in PR actions incorrectly shows deleted tasks and gets stuck

### ISSUE THREAD

**Issue by Sergio0694** [actions/runner#1539]
**Describe the bug**
I made some changes to [my YAML file for GitHub actions](https://github.com/Sergio0694/ComputeSharp/blob/main/.github/workflows/dotnet.yml) a while back, and specifically renamed two of the tasks there. Since then, I've noticed that those two actions still show up in the tasks list for PRs, though they just get stuck forever as "waiting", since those tasks don't actually exist in the YAML file anymore. Why are they still there? 🤔

Interestingly, this is not an issue for individual actions from the Actions tab, the pipelines there complete just fine.

**To Reproduce**
1. Go to [this PR](https://github.com/Sergio0694/ComputeSharp/pull/172)
2. Observe the two pending tasks in the tasks list below
3. See that those tasks don't actually exist in the [YAML](https://github.com/Sergio0694/ComputeSharp/blob/main/.github/workflows/dotnet.yml) file.

**Expected behavior**
Those two actions should not be there anymore, as they're not present in the YAML file.
Not really sure where GitHub is getting them from, those names just don't exist anywhere in the whole repo now.

## Runner Version and Platform
GitHub website

## What's not working?
<img width="343" alt="image" src="https://user-images.githubusercontent.com/10199417/145015735-b1c1b020-d6a1-447a-94d5-86c1188735b1.png">

**Comment by henrygriffiths** [comment]
@Sergio0694 I've had this issue before - they're likely still showing up because the checks are required by branch protection rules for the base branch of your PR (main), which is explained by the 'required' flag next to the check. 
![image](https://user-images.githubusercontent.com/42880130/145094152-b807582b-cfde-49b2-94a3-9aa4a8d5b8ec.png)
When the checks are deleted, the branch protection rules are not modified.

**Comment by Sergio0694** [comment]
Ah, that did the trick! I had completely missed the fact that rules wouldn't auto-update.
Thank you! 😄
