### ISSUE TITLE
`github.job` not available in `concurrency` context

### ISSUE THREAD

**Issue by khause** [actions/runner#1544]
**Describe the bug**
Even though `github.job` is valid syntax.. for some reason it's not being picked up in the job `concurrency` stage causing 1 job to cancel a completely irrelevant job.

**To Reproduce**
If you set the concurrency value to e.g.: `${{ github.head_ref }}::${{ github.job }}`, the value of `github.job` isn't being picked up.

**Expected behavior**
Both values of `github.head_ref` **and** `github.job` should be accessible in the concurrency context as stated here: [github context availability](https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability)

## Runner Version and Platform
Latest version running on the github.com cloud

## What's not working?
No error messages, just no value is retrieved from using `github.job` in the `concurrency` context

## Job Log Output
There is no output.

## Runner and Worker's Diagnostic Logs
N/A

**Comment by khause** [comment]
Similar to https://github.com/actions/runner/issues/1459

**Comment by TingluoHuang** [comment]
`github.job` was set by the runner when it actually run the job, that's why it can't get used on the service.
Unfortunately, even `github` context is available for `concurrency`, not all values under `github` context are available, ex: `github.action`, `github.job` and `github.workspace`.

https://github.community/c/code-to-cloud/github-actions/41 might be a better place for reporting this since the runner itself doesn't handle `concurrency`.
