### ISSUE TITLE
GH runner config exits with return code=0 after failure

### ISSUE THREAD

**Issue by rafajot1** [actions/runner#1579]
**Describe the bug**
GH runner config (config.cmd) exits with return code=0 after failure.
This was observed on Windows. I have not tested this issue on other OSes such as Linux or Mac.

Please refer to the screenshot below.

**To Reproduce**
1. Register runner using config.cmd and provide name that is longer that 64 characters
2. see the error about exceeding maximum name length
3. check error code (echo $?) which is going to return False which stands for 0. This is unexpected for the failed operation.

**Expected behavior**
config.cmd should exit with non-zero return code

## Runner Version and Platform
win-x64-2.285.1

OS of the machine running the runner? Windows

## What's not working?
![image](https://user-images.githubusercontent.com/78530629/147462596-4f1310cd-54d4-475c-a60e-3463dde3fa9a.png)

**Comment by TingluoHuang** [comment]
@fhammerl to check this, my guess is the `runner.listener.exe` exit with return code 1, but the `config.cmd` exit with 0.

**Comment by ruvceskistefan** [comment]
Hi @rafajot1,
Thanks for reported issue! I just wanted to let you know we're working on this. I definitely found that `runner.listener.exe` exit with return code 1, but `config.exe` exit with 0. I'll let you know when I solve the reported bug.

**Comment by ruvceskistefan** [comment]
Hi @rafajot1,

I investigated the reported issue and [PowerShell docs](https://docs.microsoft.com/en-gb/powershell/module/microsoft.powershell.core/about/about_automatic_variables?view=powershell-7.2) and I think that there was a misunderstanding, that is, that the problem does not exist at all. In powershell, `$?` would return `False` if the previous command failed - has a return value not equal to 0. According to the picture, `$?` correctly stated that the command failed which is expected behaviour.

Therefore, I will close this issue, feel free to reopen it if you think there is still a problem.
