### ISSUE TITLE
job.status is not updated within composite action

### ISSUE THREAD

**Issue by mike-carey** [actions/runner#1682]
**Describe the bug**

When attempting to read the `job.status` variable within a composite action specifying `if: always()`, the `job.status` is always success.

<img width="890" alt="image" src="https://user-images.githubusercontent.com/32496966/153679879-a6f0f9b9-021d-4d13-a109-af778131a377.png">

**To Reproduce**
1. Go to my demo run: https://github.com/mike-carey/ghactions-test-job-status/actions/runs/1831819778
2. Observe that the job.status is `success` when echoed under both the local Composite action as well as repo Composite action.

**Expected behavior**

I would expect the job.status to be `failure` as soon as the composite action experiences a failure.

## Runner Version and Platform
Version of your runner?

OS of the machine running the runner? OSX/Windows/Linux/...

ubuntu-latest of github-hosted runners

## What's not working?

The job.status is not being set to `failure` before the end of the composite-action run.

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

```
Prepare all required actions

> Run ./.github/actions/do-something

> Run exit [1](https://github.com/mike-carey/ghactions-test-job-status/runs/5163088095?check_suite_focus=true#step:3:1)

Error: Process completed with exit code 1.

Run echo success
success
```

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

NA

**Comment by nikola-jokic** [comment]
Thank you for this issue @mike-carey! We are reproducing the issue and we will get back to you as soon as possible 😊

**Comment by thboop** [comment]
Hey @mike-carey ,

We currently don't update the `job.status` until a composite step completes, so if you try to evaluate the job status during that time it may not give you the value you expect. This was intentional, as this could cause confusion with multiple nested composite steps.

However, we do offer the `github.action_status` which contains the result of your current composite action, which updates after each composite step. The docs talk more about it [here](https://docs.github.com/en/actions/learn-github-actions/expressions#evaluate-status-explicitly). You can check both that and your job status as well, in scenarios where if you want to know if the job failed before you started the composite action, or failed during the composite action.

Please let me know if that solves your issue, otherwise could you describe what you are trying to do in a little more detail? I'd be curious the use case so we can see what features would help solve it.

**Comment by mike-carey** [comment]
🤦 Thank you @thboop!  This does solve my issue.  Sorry about the confusion.  I usually check the [Contexts](https://docs.github.com/en/actions/learn-github-actions/contexts) page for theses kind of things and did not see `action_status` as a listed option.  I have created a [PR](https://github.com/github/docs/pull/15503) to update the docs.  Please feel free to leave any feedback if I worded incorrectly.
