### ISSUE TITLE
Multiple self-hosted runners

### ISSUE THREAD

**Issue by prachitrivedi19** [actions/runner#1788]
I have configured multiple runners for one repo. Now how to choose one particular runner out of all to run my pipeline. Is there any such configuration to select one runner with their name?

**Comment by nikola-jokic** [comment]
Hi @prachitrivedi19,

If you look at the [docs](https://docs.github.com/en/actions/hosting-your-own-runners/using-self-hosted-runners-in-a-workflow#using-custom-labels-to-route-jobs), you can specify labels and schedule your runs based on them.

**Comment by prachitrivedi19** [comment]
@nikola-jokic thank you for the reply. We are looking for something that will help us specify the runner's name in the pipeline. Let's say we have two-three runners all with the same OS and configuration then how can we choose one out of them?

**Comment by nikola-jokic** [comment]
@prachitrivedi19 you can assign a label with the name of the runner as described [here](https://docs.github.com/en/actions/hosting-your-own-runners/using-labels-with-self-hosted-runners#using-the-configuration-script-to-create-and-assign-labels). Since you can create custom labels, you can name your runner and select it based on that label.
