### ISSUE TITLE
Reusable workflows: Increase limit of called workflow depth from 2 to 3 or more

### ISSUE THREAD

**Issue by cytopia** [actions/runner#1797]
**Describe the enhancement**

I am trying to generalize my resuable workflows. By doing so I hit the maximum depth limit:
```
error parsing called workflow "./.github/workflows/build.yml@": 
job "arch" calls workflow "./.github/workflows/docker-multistage-build.yml@",
but doing so would exceed the limit on called workflow depth of 2
```
I would like to be able to allow reusable workflows to call other reusable workflows and then call the initial one in my main workflow

**Comment by nikola-jokic** [comment]
Hi @cytopia,

This is enhancement is not related to the runner, it concerns the GitHub actions platform more generally. Could you please post your feedback on the [GitHub Community Support Forum](https://github.community/c/code-to-cloud/52) which is actively monitored? Using the forum ensures that we route your problem to the correct team. :smiley:

**Comment by Jeanstephane269** [comment]
[](url)

**Comment by stefreak** [comment]
New limit is 4: https://github.blog/changelog/2022-08-22-github-actions-improvements-to-reusable-workflows-2/

**Comment by baracudda** [comment]
then why did I just now get "but doing so would exceed the limit on called workflow depth of 3"?

**Comment by e3b0c442** [comment]
Because the total depth is 4, including the top level workflow, so the _called_ workflow depth limit is 3.

That said, this really reeks of an artificial limitation or suboptimal implementation, and is extremely limiting from an encapsulation and composability perspective. I hope there are plans in progress to address whatever the root failure is and remove this limit entirely (or set it to a number that no sane workflow can reach).

**Comment by DoLoop216** [comment]
Why are github actions so behind... Depth limitations, organizing in directories limitations....

**Comment by karlosss** [comment]
it is 2026, and we still have a maximum stack size of 4 workflows... this is how i have been coding at high school, is that how github is now being developed?
