### ISSUE TITLE
Literally nobody knows when to use secrets vs envs

### ISSUE THREAD

**Issue by temurih** [actions/runner#1817]
Especially when Github has 3 different ways to set env for Github actions (recently they removed environmental variables, thank God!). Why not make everyone's life easier and have a way to view which envs/secrets are set or at least add a dropdown option that takes you to the place where you can add/update the secrets/env. One place says to use `${{env.SOME_ENV}}` and the other place says to use `${{secrets.SOME_ENV}}`, but none works for me. Even setting `Repository secrets` is useless. There is no way to know if your secrets are set or debug why they are not being pulled by the Github actions because all you get is `***`.

![image](https://user-images.githubusercontent.com/3893769/162606415-487c6d1b-b4bb-49c5-abbf-358923e28fa5.png)

**Comment by nikola-jokic** [comment]
Hi @temurih,

This enhancement is not related to the runner itself, but to the platform more generally. Could you please post your feedback on the [GitHub Feedback](https://github.com/github/feedback/discussions/categories/actions-and-packages-feedback), so the team monitoring the Feedback forum can route your request to the correct team?

Since we are trying to keep issues related to the runner itself, I will close this issue. But feel free to post this enhancement on the Feedback Forum
