### ISSUE TITLE
Self hosted runners requires latest runner version to be updated all the time!

### ISSUE THREAD

**Issue by compliance-user** [actions/runner#1843]
Hi Team,

So, this is just a quick question on why a self hosted runner should update the new release with in 30 days of time using disableupdate option? Is there a way to stop this update process. The runner should run seamlessly without updating the version every now and then.

Thanks.

**Comment by igibek** [comment]
Hey, I have the same. Even during the development process, it keeps updating. For example, I added some changes to the runner's source code to add custom functionality then I compiled and run it. However, it starts auto-update process and therefor my changes are not reflected.

**Comment by fhammerl** [comment]
Hi @compliance-user,

Good question. Generally, Github keeps the runners updated to the newest version at all times. I left a link for an older issue exploring why in detail.

With that in mind, the idea behind `--disableupdate` isn't to opt out of updating. It is to reduce the startup time and network usage of ephemeral runners, especially when running on containers. The images behind these containers are still expected to be updated on a monthly basis. 

The 30 days window is a compromise so that maintainers still have time to update their definitions to the newest runner.

[Disableupdate docs](https://docs.github.com/en/actions/hosting-your-own-runners/autoscaling-with-self-hosted-runners#controlling-runner-software-updates-on-self-hosted-runners)

[Legacy thread about why the runners always self-update](https://github.com/actions/runner/issues/246)

**Comment by fhammerl** [comment]
@igibek Thank for the comment, it's a valid complaint about the dev process, I'll bounce it off the team and see what we can do to smooth it out. 

As a workaround, feel free to change the `src/runnerversion` on your branch to a newer one to prevent an update entirely.

**Comment by aydasraf** [comment]
@fhammerl I am sorry to comment on a closed issue, but is there an API that tells the depreciated version beforehand, so we got alerted to update the runners before it crashes and causes operational interruptions?
