### ISSUE TITLE
github-actions detected as a secret

### ISSUE THREAD

**Issue by iamludal** [actions/runner#1894]
**Describe the bug**

The name "github-actions" seems to be detected as a secret, while it is not. This blocks the creation of an output if it contains this value.

**To Reproduce**

1. On any repository, create a branch named "XXX-github-actions"
2. Add a workflow with a job that sets an output containing the branch name
3. See warning in workflow run.

**Expected behavior**
This value should not be detected as a secret.

## Runner Version and Platform
Linux self-hosted

## What's not working?

![image](https://user-images.githubusercontent.com/44783088/168568679-0c501b65-a352-46e6-8b41-cb57243d6c31.png)

![image](https://user-images.githubusercontent.com/44783088/168568625-46755ae1-b26a-427d-b0e5-38e6def38bdc.png)

**Comment by thboop** [comment]
Hey @iamludal , this is typically caused by a repo or org secret (or an action using the `::add-mask::` command).

This doesn't reproduce in my test repo, here are the logs

```
Run echo "-github-actions"
  echo "-github-actions"
  shell: /usr/bin/bash -e {0}
-github-actions
```

If you have registered structured data (like json) as a secret, you typically see issues like this, you can read our docs for more [information](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-secrets)

Could you try reproducing this in a public repo under your user account and post a link to that run?

**Comment by iamludal** [comment]
Hi @thboop, indeed I was not able to create a minimal reproducible example. It seems like something strange is happening with my workflow. I'll try to investigate by myself in the following days. Thanks for your response!

**Comment by iamludal** [comment]
I think there is definitely a problem with the `github-actions` keyword, see the warning messages below. 😄 
The full URL is: `https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12`
![image](https://user-images.githubusercontent.com/44783088/198244624-dfd08bae-3e6f-4e2e-af49-e4e1fdd2bcd1.png)
