### ISSUE TITLE
Unrecognized named-value: 'env' error for jobs.<job_id>.container

### ISSUE THREAD

**Issue by ubiuser** [actions/runner#1915]
**Describe the bug**
Usage of `env` in `jobs.<job_id>.container` results in invalid workflow.

**Expected behavior**
`env` should be available as per https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability.

## What's not working?

**Error message**
```
[Invalid workflow file: .github/workflows/integration.yml#L11](https://github.com/99designs/gqlgen/actions/runs/2384254132/workflow)
The workflow is not valid. .github/workflows/integration.yml (Line: 11, Col: 16): Unrecognized named-value: 'env'. Located at position 1 within expression: env.GO_VERSION .github/workflows/integration.yml (Line: 21, Col: 16): Unrecognized named-value: 'env'. Located at position 1 within expression: env.GO_VERSION
```

**Relevant code**
https://github.com/99designs/gqlgen/blob/b262e40a485f67d2659e239a156418938d0fe2e9/.github/workflows/integration.yml

## Job Log Output
https://github.com/99designs/gqlgen/actions/runs/2384254132

**Comment by nikola-jokic** [comment]
Hi @ubiuser,

Thank you for submitting this issue! The issue is not related to the runner (the runner never receives this workflow), but the service parsing your workflow file. Could you please post this issue on the [GitHub Feedback](https://github.com/github/feedback/discussions/categories/actions-and-packages-feedback)? Using the forum ensures that we route your problem to the correct team. :smiley:

**Comment by ubiuser** [comment]
https://github.com/github/feedback/discussions/17311
