### ISSUE TITLE
settings->actions->runners  This page is taking too long to load.

### ISSUE THREAD

**Issue by fmadhi19** [actions/runner#1926]
**Describe the bug**
When I try to load settings->actions->runners,
The unicorn page loads with this message;

This page is taking too long to load.

Sorry about that. Please try refreshing and contact us if the problem persists.

**To Reproduce**
 settings->actions->runners,

**Expected behavior**

## Runner Version and Platform
Version of your runner?

OS of the machine running the runner? OSX/Windows/Linux/...

## What's not working?
Please include error messages and screenshots.

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by nikola-jokic** [comment]
Hey @fmadhi19,

Thank you for submitting an issue, but this issue is not related to the runner itself. Whenever this happens, the team is notified and is resolving the issue right away. I will close this issue since we are trying to keep issues related to the runner itself, and sorry for the trouble it may have caused you. :relaxed:
