### ISSUE TITLE
Automatically switch to Github runner if self hosted runner is not available

### ISSUE THREAD

**Issue by aditishah-dev** [actions/runner#1969]
**Describe the enhancement**
Add support in Github action which will pick Github runner if self hosted runner is not available automatically.
e.g. Setup single self hosted runner. If it is available then pipeline should run using  self hosted runner and if it is not then pipeline should use Github Runner and complete its job.

**Comment by nikola-jokic** [comment]
Hi @aditishah-dev,

Thank you for submitting this enhancement. The proposal is really related to the GitHub actions platform more generally. Can you please post this feature request to the n the [GitHub Feedback](https://github.com/github/feedback/discussions/categories/actions-and-packages-feedback) site which is actively monitored. Using the forum ensures that we route your problem to the correct team. :smile: 

I will close this issue now, because we try to keep issues related to the runner itself. Since this is really about the service picking up where to distribute work, it does not require changes to the runner.

**Comment by aditishah-dev** [comment]
@nikola-jokic Thanks for the guidance. Added FR to https://github.com/github-community/community/discussions/20019

**Comment by beingminimal** [comment]
Hi @nikola-jokic No one is replying in [Feedback](https://github.com/github-community/community/discussions/categories/actions-and-packages-feedback).  Can you please suggest some other way?

**Comment by aditishah-dev** [comment]
@nikola-jokic Okay....let's wait for one week at-least😊

**Comment by zymotik** [comment]
@nikola-jokic 602 days later and.... the feature is still "unanswered" after 109 votes and plenty of activity. What does it take to get a reply from Github?

**Comment by zymotik** [comment]
FYI: I posted the question "[How can I get a Github actions job to use a different runner if the first runner is already busy or unavailable](https://stackoverflow.com/questions/78062700/how-can-i-get-a-github-actions-job-to-use-a-different-runner-if-the-first-runner)" to StackOverflow community too.
