### ISSUE TITLE
The SSL connection could not be estabilished

### ISSUE THREAD

**Issue by danielscatigno-ncpc** [actions/runner#1986]
OS: Windows Server 2012 R2
Actions-Runner 2.294.0

When running the configure command config.cmd I got an error

I also tried to Invoke-WebRequest as sugested in #902 

Invoke-WebRequest -Uri https://pipelines.actions.githubusercontent.com/AqwOkDKd9ML1YXY7Ny44c1sLw4OlA0OJSarpYgouGuPst6OjDA/_apis/connectionData

But I get the error:
Invoke-WebRequest : The underlying connection was closed: An unexpected error occurred on a send.
At line:1 char:1
+ Invoke-WebRequest -Uri https://pipelines.actions.githubusercontent.com/AqwOkDKd9 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], Web
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

Also checking the logs of the config command:
[Runner_20220706-141315-utc.log](https://github.com/actions/runner/files/9071666/Runner_20220706-141315-utc.log)

I've tried to Invoke-WebRequest to others https sites and they are working.

**Comment by nikola-jokic** [comment]
Hi @danielscatigno-ncpc,

What it seems to me is that system config related to parsing certificate for this API is not supporting certificate of [pipelines.actions.githubser](https://pipelines.actions.githubusercontent.com)[https://pipelines.actions.githubusercontent.com](https://pipelines.actions.githubusercontent.com/AqwOkDKd9ML1YXY7Ny44c1sLw4OlA0OJSarpYgouGuPst6OjDA/_apis/connectionData). Since the `Invoke-WebRequest` does not work as well, it is unlikely that this issue is related to the runner.

Did you manage to make it work? As for `Invoke-WebRequest` working for other sites, different sites have different signatures, so maybe this type of signature is not configured. Perhaps this can help: https://github.com/actions/runner/blob/main/docs/checks/sslcert.md tracking down the problem.

**Comment by nikola-jokic** [comment]
I'm going to close out this issue until we hear back from you, please let us know if you are still seeing this issue!

**Comment by danielscatigno-ncpc** [comment]
> Invoke-WebRequest -Uri https://pipelines.actions.githubusercontent.com/AqwOkDKd9ML1YXY7Ny44c1sLw4OlA0OJSarpYgouGuPst6OjDA/_apis/connectionData

I have not managed to get it working, I've tried the mentioned Link, without success, I've downloaded and installed(Trusted) the certificate from Google Chrome

The curious thing is the address doesn't work on Internet Explorer either

**Comment by danielscatigno-ncpc** [comment]
Another thing to point is that: shouldn't a WebRequest to a non SSL using HTTP work?
Example:
`Invoke-WebRequest -Uri http://pipelines.actions.githubusercontent.com/AqwOkDKd9ML1YXY7Ny44c1sLw4OlA0OJSarpYgouGuPst6OjDA/_apis/connectionData`

this works fine on my Machine but not on the server

**Comment by LucioPelinson** [comment]
@nikola-jokic I have the same problem in last version
git works, but self hosted do not work

![image](https://user-images.githubusercontent.com/28662273/190022327-8df50fc0-bfcd-4a21-8a87-92d2341fd5ba.png)

**Comment by gumbarros** [comment]
@LucioPelinson  solved with:
https://github.com/microsoft/azure-pipelines-agent/issues/3722#issuecomment-1026292351
