### ISSUE TITLE
Python 3.10 is taken as Python 3.1 in github action workflows

### ISSUE THREAD

**Issue by ecedreamer** [actions/runner#1989]
**Describe the bug**
In github workflow file, I have written  strategy: matrix: python-version: [3.8, 3.9, 3.10] . But 3.10 is understood as 3.1 . So its a clear bug since python 3.10 exists. 

**To Reproduce**
1. Go to actions and generate workflow for Django app. 
2. edit python-version including 3.10
3. commit and raise a new PR to see the issue. 

**Expected behavior**
Should recognize Python 3.10 as 3.10 not 3.1

**Comment by nikola-jokic** [comment]
Hi @ecedreamer,

This issue is related to the way we parse yaml. You can reference this comment for further information: https://github.com/actions/runner/issues/849#issuecomment-1033084425

Since the value should be treated as a string, try adding `'` around `'3.10'`.
Please, let us know if this solves your problem :relaxed:

**Comment by ecedreamer** [comment]
Thanks @nikola-jokic , It worked. Good day 😊😊😊!!
