### ISSUE TITLE
Debug logs for the if condition of skipped jobs

### ISSUE THREAD

**Issue by roryabraham** [actions/runner#1995]
**Describe the enhancement**
When a job is skipped because it's `if` condition is not met, it's very difficult to debug why that happened. It would be valuable to be able to see debug logs for the evaluation of the job-level `if` condition.

**Additional information**
It's sometimes possible to work around this by creating another job without a conditional and then creating steps with the same `if` condition that is used at the job-level for another job. However, it's inconvenient and not safe to assume that the evaluation of a condition is going to be the same at the job and step level. Here's an example where the same `if` condition is used for a job and a step, and the step runs but the job does not:

https://github.com/Expensify/App/runs/7312387282?check_suite_focus=true

NOTE: if the feature request has been agreed upon then the assignee will create an ADR.   See docs/adrs/README.md

**Comment by fhammerl** [comment]
Hi @roryabraham, thanks for reporting this, especially demonstrating the workaround by adding an extra job to log the job conditions using individual steps, hopefully this increases the visibility for users running into the same issue.

This feature request cannot be implemented in the runner. The decision whether to run a job is made server-side and only jobs to be executed are sent to the runner.

I'd recommend starting a discussion on the community forum linked below about this and perhaps increasing the clarity of the UI to prevent confusing situations like https://github.com/actions/runner/issues/1996.

I'm closing the issue due to 👇

This issue does not seem to be a problem with the runner application, it concerns the GitHub actions platform more generally. Could you please post your feedback on the [GitHub Community Support Forum](https://github.community/c/code-to-cloud/52) which is actively monitored. Using the forum ensures that we route your problem to the correct team. 😃

**Comment by roryabraham** [comment]
Thanks for responding @fhammerl! I posted a forum topic [here](https://github.community/t/debug-logs-for-the-if-condition-of-skipped-jobs/261822). Even if nothing comes of it, hopefully it might help others who find themselves with the situation I had in https://github.com/actions/runner/issues/1996

**Comment by lesteve** [comment]
> I posted a forum topic [here](https://github.community/t/debug-logs-for-the-if-condition-of-skipped-jobs/261822).

Looks like the discussion is now available here: https://github.com/orgs/community/discussions/20640

**Comment by Crisfole** [comment]
This continues to be extremely difficult to debug....

**Comment by tylermilner** [comment]
> This continues to be extremely difficult to debug....

I agree. I spent a few hours trying to figure out why my job was always being _skipped_. For anyone experiencing this, I wrote about how I solved it in my case in the [community discussion thread](https://github.com/orgs/community/discussions/20640#discussioncomment-6267202).
