### ISSUE TITLE
Remove directory restriction for (reusable) workflows

### ISSUE THREAD

**Issue by flobernd** [actions/runner#2102]
**Describe the enhancement**

Currently all workflows must be rooted in the `.github/workflows` directory. With that restriction it's not possible to use subdirectories to organize your workflows.

While this might seem like a minor issue, it got a lot more annoying with the introduction of reusable workflows. Many companies are maintaining repositories with the single purpose to hold all of their standard workflows. This often includes workflows for multiple programming languages.

It would be really great if we could use subdirectories like `.github/workflows/{lang}` instead of being forced to use `{lang}-build.yaml` names.

It would as well be great if **reusable workflows** (I see the need to enforce it for regular workflows) are allowed to be rooted in any directory outside of `.github/workflows`. This would make the directory structure of "workflow repositories" way more intuitive.

This change would be completely backwards compatible as the current syntax for calling workflows by relative pathes require you to use the complete path relative to `$GITHUB_WORKSPACE` anyways:

```yaml
uses: ./github/workflows/target.yaml
```

**Comment by nikola-jokic** [comment]
Hey @flobernd,

Thank you for reporting this! Since this is not related to the runner, it concerns the platform more generally, could you please post your feedback on the [GitHub Feedback](https://github.com/github/feedback/discussions/categories/actions-and-packages-feedback)? Using the forum ensures that we route your feature request to the correct team.

I will close this enhancement now since it does not require changes on the runner but feel free to write any comments here. If the change on the runner is needed in the future, I will re-open this issue :relaxed:

**Comment by umarcor** [comment]
FTR:

- https://github.com/orgs/community/discussions/9050
- https://github.com/actions/runner/issues/1493
- https://github.community/t/allow-reusable-workflows-to-be-located-at-arbitrary-locations-and-be-local/212745

> Hi @umarcor and @PathogenDavid, we just released the ability to reference a local reusable workflow: [github.blog/changelog/2022-01-25-github-actions-reusable-workflows-can-be-referenced-locally](https://github.blog/changelog/2022-01-25-github-actions-reusable-workflows-can-be-referenced-locally)

> @jenschelkopf is {path} still hardcoded to .github/workflows?

That was 7-8 months ago. Didn't get any further response from any GitHub employee so far.

**Comment by flobernd** [comment]
Just saw it when following your link from the other issue 😞 No reply to my discussion either. Seems like there is a ton of stuff that needs to be refactored in order to make workflows more dynamic.
