### ISSUE TITLE
Latest release is not showing up first anymore

### ISSUE THREAD

**Issue by npalm** [actions/runner#2151]
**Describe the bug**
On the release page the latest release is not showing up first anymore, looks like may old releases are re-released. We are using the github api to find the latest release. To cache the self-hosted action action runner distribution. This is now downloading a not supported release, in our case 2.293.1 instead of the latest one. This release is not starting.

**To Reproduce**
Just go to the release page of this repo, or query via the API.

**Expected behavior**
Latest release shows up first.

## Runner Version and Platform
n/a

## What's not working?
n/a

## Job Log Output
n/a

**Comment by nikola-jokic** [comment]
Hey @npalm, thank you for spotting this!

**Comment by fhammerl** [comment]
Hi @npalm,

You're totally right about some older releases being re-released. However, they were tagged as pre-release so that they don't interfere with getting the _latest_ runner version through the API.

When you query the (list of releases)[
https://docs.github.com/en/rest/releases/releases#list-releases], they are returned ordered by release date, most recent first. 

If you need the latest release by version, it is best practice to fetch it though its dedicated API endpoint:
https://docs.github.com/en/rest/releases/releases#get-the-latest-release

This endpoint returns with the correct version.

Closing this issue as per https://github.com/philips-labs/terraform-aws-github-runner/pull/2455/files

**Comment by npalm** [comment]
Thx for the feedback.
