### ISSUE TITLE
Unreliable Cron in runners

### ISSUE THREAD

**Issue by hollesse** [actions/runner#2219]
**Describe the bug**
I have a job which should run every 5 Minutes according to the Github Actions Docs this is the smallest value which is possible. I know see a maximum of 2 builds per hour sometimes there is not even 1 build per hour. I saw there was Issue #877 already, but this was closed. IMHO with this bug scheduled jobs are unusable. 
**To Reproduce**
```yaml
on:
  schedule:
    - cron: '*/5 * * * *'
```
But you can also have a look at our smoketests job https://github.com/remotemobprogramming/timer/actions/workflows/smoketest.yml

**Expected behavior**
I should see 12 Jobs running per hour and not just 2 or even less.

## Runner Version and Platform
ubuntu-latest

**Comment by nikola-jokic** [comment]
Hey @hollesse,

Thank you for raising this issue! Since this is not really the runner's responsibility, it concerns the platform more generally, can you please post your feedback on the [GitHub Feedback](https://github.com/github/feedback/discussions/categories/actions-and-packages-feedback) site which is actively monitored? Using the forum ensures that we route your problem to the correct team.

I will close this issue now because we try to keep issues scoped to the runner itself :relaxed:
