### ISSUE TITLE
GitHub Action step is hanging until timeout

### ISSUE THREAD

**Issue by mattyrob** [actions/runner#2298]
**Describe the bug**
An GitHub action to run QUnit tests that has worked well for some time stopped working around the 22nd of December. The process runs on Linux using `ubuntu-latest`.
On finding [this blog article](https://github.blog/changelog/2022-12-01-github-actions-larger-runners-using-ubuntu-latest-label-will-now-use-ubuntu-22-04) we have specified the workflow to use `ubuntu-20-04` and the workflow is now operational again.

Possibly associate to [bug](https://github.com/actions/runner/issues/2244)

**To Reproduce**
1. Example workflow such as [here](https://github.com/ClassicPress/ClassicPress/blob/develop/.github/workflows/javascript-tests.yml)
2. Specify `ubuntu-latest` as runner.
3. Any run of the process fails, `push`, `pull_request` and `workflow_dispatch` all failed.

**Expected behavior**
This workflow should still run and complete as normal using `ubuntu-latest` in place of `hubuntu-20.04`

## Runner Version and Platform
Previouslt when failing `ubuntu-latest`, now functional with `ubuntu-20-04` as above:
See workflow definition:
`https://github.com/ClassicPress/ClassicPress/blob/develop/.github/workflows/javascript-tests.yml`

OS of the machine running the runner? OSX/Windows/Linux/...

## What's not working?
The process runs as expected until the final step where the process hangs without further log output until the process is terminated after running without completing at 6 hours.
See log here:
https://github.com/ClassicPress/ClassicPress/actions/runs/3559500265

## Job Log Output
Log output accessible at link above, full list of job logs starts:
https://github.com/ClassicPress/ClassicPress/actions/workflows/javascript-tests.yml

## Runner and Worker's Diagnostic Logs
N/A

**Comment by nikola-jokic** [comment]
Hey @mattyrob,

Thank you for reporting this! This issue does not seem to be a problem with the runner application, it concerns the software on machines running GitHub's hosted runners. Could you please post your issue in the [Virtual Environments Repository](https://github.com/actions/virtual-environments/issues/new/choose) to ensure the correct team sees it. :relaxed: 
I will close this issue here, to keep the board scoped to the runner. But please reference this issue or copy it. You have explained the issue really well!
