### ISSUE TITLE
Please support something like "allow-failure" for a given job

### ISSUE THREAD

**Issue by mvo5** [actions/runner#2347]

**Comment by mathieujobin** [comment]
if this branch protection setting could be an exclude list instead of having to specify all dozens of checks to be required and keeping it up to date, it would make things much easier.

but being able to control it via the .yml file would obviously be much easier to maintain long term.

![image](https://user-images.githubusercontent.com/99191/210188485-fb4ae301-adfb-4931-8643-c00611268a22.png)

**Comment by dersimn** [comment]
I‘d need something like this to allow a whole workflow to be optional (not getting a notification on failure).

It‘s a workflow with a task like „Check if parent Docker Image was updated“ with a nightly run. If there was no update the Job fails and I’ll get a notification about failure, but in this case the job is designed to fail (most of the time) and should not spam my mails.

This one here: https://github.com/dersimn/HelloARM-GitHub-Workflow/blob/master/.github/workflows/auto-build-on-base-image-change.yml

**Comment by sigprof** [comment]
@dersimn
Instead of making `check-job` fail when no update is needed, you can add an output to report the result of the check without failing the job:
```yaml
  check-job:
    outputs:
      needs-updating: ${{ steps.check.outputs.needs-updating }}
```
Then remove the `Check result` step and use `if: needs.check-job.outputs.needs-updating != 'false'` in the `trigger-build` job; this way you won't have failures when no updating is needed (the `trigger-build` job would just be marked as `skipped`).

**Comment by zackees** [comment]
I am a maintainer of FastLED and we have a bunch of platforms that we don't support yet like the esp32c2.

I want to track which builds are expected to succeed and which are allowed to fail. However we don't have this feature yet so I just don't run those optional builds on all pulls.

This seems like an easy feature to put in and it seems like Microsoft is wasting more time dealing with the community requesting this than actually implementing the feature.

Just implement the feature and stop wasting time on dealing with the community requesting it!

**Comment by EwoutH** [comment]
![image](https://github.com/user-attachments/assets/c2e45c12-0f5f-47c1-9700-94102c2f0d00)
 
![image](https://github.com/user-attachments/assets/a69d3edf-7cad-4c65-acb4-e0a085ea3496)

At some point the GitHub Actions runners will get a new product owner and be like - What? Really?! Why?! HOW?!?!

**Comment by LecrisUT** [comment]
You see, the key point is to make sure it's marked closed so that nobody actually looks into it. I believe last I read about this topic the main people who were working on this were laid-off or something to that extent.

On a brighter note, this is probably one of those issues that everyone who has managed github actions is present (insert relevant xkcd here - 2363?), so you can use it to give a quick message to everyone.

---

Hello everyone, hope you will have a lovely day! Thank you for your work on your github workflows implementations, it is great to see what enginious approaches you've developed, they've been a great inspiration!

**Comment by EwoutH** [comment]
You know what, let's get some current GitHub runner developers in the party!

Hi @TingluoHuang, @ericsciple, @rentziass, @nikola-jokic, @joshmgross, @AllanGuigou and @luketomlinson!

I'm tagging you all from the _most upvoted issue_ on this repo _ever_! Who doesn't want the bragging rights that (s)he unblocked the most requested feature in GitHub Actions history?

What do you say, that's not enough? Go implement it, it's probably only a couple hours. And then you can rightfully claim you made the largest amount of users happy in one single blow!

You guys rock and you can do this! 🚀🚀🚀

**Comment by nebuk89** [comment]
Sorry I missed this one as it was marked as closed (I am not an admin yet so cannot re-open!). We are currently going through adding paper cut sized items to our backlog for this year (you will see me/ @Steve-Glass and @lkfortuna trying to get through the backlog :) )

I have added this and will dig in with the team today how big this is/any concerns to see when we can get this one added. Where I am trying to comment on a bunch of these issues my GitHub notifications are now 🔥 so please be patient as I try to get back round here :)

**Comment by mathis-la-debrouille** [comment]
Drone and others have it, and while it may seem minor, good UI for CI is incredibly important. I hope to see this 'on' soon.

**Comment by wsanchez** [comment]
I got sufficiently tired of this that I came up with a work-around. Posting it here in case others find it useful:

> https://github.com/burningmantech/ranger-ims-server/pull/1347/files

What I did gets me:
-  a green checkmark for the job (not great, but this is the trade-off we are making)
- a green checkmark for the workflow (the goal here)
- a comment in the PR indicating that an optional build failed (replacement for red checkmark for the job)

<img width="919" alt="Screenshot 2024-10-31 at 10 42 26 AM" src="https://github.com/user-attachments/assets/c5de2579-153a-43c4-827e-8a41a074d828">

**Comment by Caellian** [comment]
@wsanchez Thank you. That support for a yellow exclamation mark instead of a green chackmark is basically the "good UI for CI is incredibly important" part.

So until we get the (apparently) super difficult to implement different status value in DB, complicated backend support for `if (step.allow_failure && step.failed) { status = warn } else { existing logic }`, and advanced yellow color support the likes of which even CIE can't comprehend in frontend, that's sadly the best DX that can be supported.

Management is probably too busy bringing 3 new LM models to Copilot - a gimmick for investors that will wow them for precisely maybe another quarter - to push for actually useful features to the product, that most devs want and need.

**Comment by sthibaul** [comment]
I would need this as well... To be able to have non-regression testing even when we know we have some failures that we will handle later.

**Comment by ljharb** [comment]
That seems to only work if all your jobs are in the same workflow file, unfortunately.

**Comment by jacobtomlinson** [comment]
It looks like a good solution for branch protection rules, but it will still show the PR with an ❌ as the overall status.

**Comment by bswck** [comment]
> It looks like a good solution for branch protection rules, but it will still show the PR with an ❌ as the overall status.

Yeah, I ended up finally not using it just because of that :/

**Comment by mansona** [comment]
I built something that takes a different approach: https://github.com/mainmatter/continue-on-error-comment

It shows the overall PR as a ✅ and adds a comment if any of the jobs with continue-on-error have failed. The only drawback right now is I haven't closed the loop on being able to make this work for PRs from people's forks but I know there are some workarounds for that

**Comment by pboling** [comment]
@mansona Does your solution work with multiple workflows?  The previous one posted only works when all jobs are in the same workflow.

**Comment by JakeQZ** [comment]
> But I do understand this is a bit of a specific request

It's not a specific request.  We all have this problem.  E.g. we run code coverage via Coveralls as part of a GitHub action.  Quite often the (Coveralls) server is offline, which results in the CI/PR checks failing.  But the code coverage report is information only.  It's lack of availablity should not block the merge.

**Comment by webknjaz** [comment]
> That seems to only work if all your jobs are in the same workflow file, unfortunately.

@ljharb yep. This is why when I was integrating it into CPython, and they had several workflows that were conditionally skipped, I came up with an idea of structuring in-repo automation as a bunch of “modules”. And by modules I mean reusable workflows. Those workflows are only allowed to contain `workflow_call:` and are prefixed with `reusable-`. And then, there's a top-level workflow that configures all the triggers you want, job skipping, inter-job dependencies, matrixes. This top-level workflow can then have alls-green: https://github.com/python/cpython/pull/103914 / https://github.com/python/cpython/pull/97533. This was during EuroPython 2023 Sprints, and so I was able to explain the ideas to the core devs in person to get things going (initially, I wasn't planning restructuring the workflows, but Łukasz Langa pointed out that weakness with having multiple workflows and I ended up inventing this approach on the spot).

Later on, I realized that the concept of modularization is a good idea regardless and started using it more in other places. It really transformed my perception of building blocks and helped create abstraction layer separation in my automations!

Just look at this: https://github.com/sphinx-contrib/sphinxcontrib-towncrier/blob/53943d5/.github/workflows/ci-cd.yml#L349-L528.

An amusing moment for me was when during PyCon US 2024 Sprints, I was talking to some Python Core dev who started advertising the automation in the CPython repo, with modularization and with alls-green. It was difficult to maintain a straight face as that person didn't realize I invented and integrated things he was so fascinated about in the moment :)

**Comment by mansona** [comment]
> [@mansona](https://github.com/mansona) Does your solution work with multiple workflows? The previous one posted only works when all jobs are in the same workflow.

Hey sorry I missed this one. Yes my solution does work with multiple workflows, it adds each "allowed failure" workflow to the existing comment 👍

**Comment by ioquatix** [comment]
@nebuk89 any update?

**Comment by nebuk89** [comment]
No updates yet, other than fixing where this got closed :) still tracking this item though so it's something we are aware of. We are still trying to hit our top community items over the next 12 months and this is on that list so watch the space I hope 🤞

**Comment by JakeQZ** [comment]
`fail-on-error: false` seems to work - see https://github.com/MyIntervals/PHP-CSS-Parser/pull/1551.

**Comment by pboling** [comment]
That's a feature / option of the coveralls action, not of github actions generally.
```
              uses: coverallsapp/github-action@v2
              with:
                  fail-on-error: false
```

**Comment by lilydjwg** [comment]
> `fail-on-error: false` seems to work - see [MyIntervals/PHP-CSS-Parser#1551](https://github.com/MyIntervals/PHP-CSS-Parser/pull/1551).

@JakeQZ It doesn't work as "allow-failure" did: what we want is that the job itself fails but doesn't impact the overall result; the job does not pretend it succeeds because nobody would look into it even when should (i.e. when a new Python release is near, I want to know if my project works with it or not).

**Comment by JakeQZ** [comment]
> It doesn't work as "allow-failure" did

I thought `allow-failure` was a proposal in the OP, rather than something that actually ever existed.

**Comment by ljharb** [comment]
@JakeQZ it's never existed in GHA - but it already exists in every single other alternative CI provider that has ever existed.

**Comment by lilydjwg** [comment]
It existed in Travis CI, which provided free CI service for opensource GitHub projects years ago.

**Comment by DavidAntliff** [comment]
The response from GitHub on this and other related issues is just stupid. I'm not going to go into detail about how badly GitHub has missed the mark on this, but the numerous comments and threads just show that they simply don't understand the core problem with the majority of "continue-on-error" use-cases.

And I know why too - so many Actions and GitHub features fail in random ways at random times, and are automatically retried until they succeed, so having them appear red would be confusing. But rather than fix those issues, we're told by their support team to "write your own retry wrappers". I'm getting really sick of the numerous 401 and 403 errors thrown up by GitHub.

Anyway, I suggest they go tinker with GitLab for a bit - a company that knows what it's building and who they are building it for - and they'll quickly see that "continue-on-error" jobs are marked **orange**, making it very clear that something went wrong but the pipeline continued anyway. Whenever I see an orange job or workflow I know instantly what's going on.

Seeing nothing but green when an error has occurred causes cognitive dissonance and is, frankly, objectively stupid.

**Comment by atkinsonm** [comment]
I recently tested whether the Checks API `neutral` conclusion can be used as a workaround for this. Findings:

**What works:**
- Creating a *separate* check run via `POST /repos/{owner}/{repo}/check-runs` with `conclusion: neutral` works. It renders with a distinct icon (grey, shown as "skipping" in the CLI).
- PATCHing a job's own check run mid-execution to `conclusion: neutral` is accepted by the API.

**What doesn't work:**
- The runner always overwrites the job's conclusion at job completion, so any PATCH to `neutral` during the job is clobbered by the final `success` or `failure`.
- Creating a second check run with the same name doesn't collapse with the job's auto-reported check — you end up with two entries.

**Conclusion:** The server-side *already supports* `neutral` as a conclusion. The gap is that the runner unconditionally sets the conclusion at job completion with no way to override it. A `conclusion` or `allow-failure` job-level property that tells the runner to report `neutral` instead of `failure` would solve this without any server-side changes.

The current workarounds are:
1. `continue-on-error: true` — hides failures behind a green checkmark (defeating the purpose)
2. Let the job fail, mark it non-required — shows a red X which implies something is broken when it's just advisory
3. Create a separate check run via the API — results in two check entries for one logical check

None of these provide the "warning" semantics that `neutral` was designed for.

**Comment by ljharb** [comment]
could a workflow_dispatch be set up that runs separately, and overrides the failure to neutral?

**Comment by atkinsonm** [comment]
> could a workflow_dispatch be set up that runs separately, and overrides the failure to neutral?

You'd need to use `workflow_run` to make it automated and you'd need an app token or PAT (the built-in `GITHUB_TOKEN` can't modify check runs created by the runner in a different workflow). You'd also have a brief window between the original workflow and the `workflow_run` where the check would show the original exit behavior of ✅ or ❌. It's technically doable but more complex than it should be.
