### ISSUE TITLE
Incorrect relative time in github action run

### ISSUE THREAD

**Issue by AndreyDodonov-EH** [actions/runner#2359]
**Describe the bug**
Relative time of workflow run is displayed incorrectly in terms of days.
At least for the local runner.
As you can see, the run was on the evening of 2023-01-07 (both started and failed), GMT+1.
Time on the local runner, as well as the time of the machine where screenshot was taken, is GMT+1.

It is 2023-01-09 as can be seen in the screenshot, but build failure shows YESTERDAY for 2023-01-07, which is super misleading.

![image](https://user-images.githubusercontent.com/44361144/211286050-4ab6d70d-8b88-45c7-91c5-0a834aa7c2b9.png)

**Expected behavior**
Relative time should be two days ago. Also, it would be nice to have an option to show absolute time instead of relative time.

OS of the machine running the runner?
Linux Ubuntu 20.04

**Comment by nikola-jokic** [comment]
Hey @AndreyDodonov-EH,

Thank you for raising this issue! This issue is not related to the runner. The https://www.npmjs.com/package/@github/relative-time-element package changed the way to round time. Do you mind submitting this issue [there](https://github.com/github/relative-time-element/issues)?

I will close this issue now since it is not related to the runner itself :relaxed:

**Comment by fhammerl** [comment]
https://github.com/github/relative-time-element/pull/234 <--- here's the exact change modifying the behaviour recently (~few weeks ago)
