### ISSUE TITLE
Ubuntu-latest: running perf produces weird garbled output

### ISSUE THREAD

**Issue by VioletGiraffe** [actions/runner#2402]
The `ubuntu-latest` runner produces weird garbled output from the `perf` commands. I suspect this may not actually be a bug in the runner per se, but it is very weird and I don't understand what's happening.

This is what i'm invoking:
`sudo perf record ./tests/bin/release/test-app [dbwal]`

More [here - this is the actual job](https://github.com/VioletGiraffe/cpp-db/actions/runs/4019125644/jobs/6905583700). Go to "Linux - running tests" and scroll down a bit.

And this is the output I'm seeing - I can't even copy-paste it here as text:
![image](https://user-images.githubusercontent.com/1175926/214953273-df053dfc-6171-491c-a2e3-1744ba73b3e2.png)

P. S. The suggested forum link "https://github.community/c/code-to-cloud/52" is no longer working, it redirects to https://github.com/orgs/community/discussions/, and I didn't find a suitable section for my question there.

**Comment by FedeDP** [comment]
Ehy @VioletGiraffe did you find any explanation/a way to solve this?
Thanks :)

**Comment by VioletGiraffe** [comment]
No, I did not, I gave up. Perf in general doesn't work very well, you're much better off profiling on Windows.

**Comment by FedeDP** [comment]
Thank you anyway, worth a shot!

**Comment by FedeDP** [comment]
If you are still interested, it seems like this patch is the culprit: https://lore.kernel.org/lkml/tip-d7065adb9b4f3384c2615f0a3dbdb6c3aae1eb18@git.kernel.org/T/ 
So that `perf record` detects that gha stdout is redirected to a pipe and prints its data to stdout instead of `perf.data` file.
Adding `-o perf.data` fixed the bug for me: https://github.com/falcosecurity/libs/pull/1918/files#diff-82c5d303a285e8cb2370945e1bb58c7f6c6d57b09ac32ed9b69ac619591b1030R38

**Comment by VioletGiraffe** [comment]
Wow, great find, thanks a lot!
