### ISSUE TITLE
Windows runner failing with LNK1318 (disk full) during Rust build

### ISSUE THREAD

**Issue by milesj** [actions/runner#2491]
**Describe the bug**

My Rust project has spuriously started to fail in CI when cargo building on Windows. It fails when linking and the error code is LNK1318, which looks to be an out of space error.

This doesn't happen on all PRs, but most of them. What's weird is that I've actually been removing crates/dependencies, which should reduce the build size.

**To Reproduce**

Only happens in my projects CI: https://github.com/moonrepo/moon/actions/runs/4442633676/jobs/7799052190?pr=711

**Expected behavior**

Windows builds don't fail or run out of space.

## Runner Version and Platform

Version of your runner? latest
OS of the machine running the runner? windows

## What's not working?

```
 = note: LINK : fatal error LNK1318: Unexpected PDB error; FILE_SYSTEM (3) 'D:\a\moon\moon\target\debug\deps\node_test-902c6729467a3585.pdb'
          

error: could not compile `moon_cli` due to previous error
warning: build failed, waiting for other jobs to finish...
error: linking with `link.exe` failed: exit code: 1201
```

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

Example job: https://github.com/moonrepo/moon/actions/runs/4442633676/jobs/7799052190?pr=711

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

Not sure how to grab this?

Anyways, here's an example job with debugging enabled: https://github.com/moonrepo/moon/actions/runs/4442633676/jobs/7799259589

**Comment by Manishearth** [comment]
We're getting something similar with https://github.com/unicode-org/icu4x/pull/3327. Other PRs have not had this issue, and this PR has had this issue on every push (including when it was a different PR, before rebasing).

https://github.com/unicode-org/icu4x/actions/runs/4703193310/jobs/8341383609?pr=3327

Annoyingly, all this PR does is change versions: if you look at the lockfile there's no actual change in the deps being pulled in. It should have no effect on compiled binaries.

The build also seems to reliably fail at the point it reaches the verify-zero-copy test, which does use a custom allocator but isn't very fancy otherwise. Any changes to that test in my PR are my attempts at fixing/diagnosing this.

**Comment by eddyb** [comment]
> Annoyingly, all this PR does is change versions: if you look at the lockfile there's no actual change in the deps being pulled in. It should have no effect on compiled binaries.

Don't Cargo package version numbers turn into `-C metadata=...` and/or the hashes in file suffixes?

Maybe the issue here is some automated caching of the `target` dir, so CI starts already with a lot of disk space being used, and then suddenly you're now creating *new files* instead of replacing the existing ones.

If you're unlucky with the contents of a test, its PDB could easily be orders of magnitude larger than the smaller ones, so by its constitution alone could push disk usage past its limit.

> which does use a custom allocator but isn't very fancy otherwise

Yeah that sounds like an easy way to get a PDB that's 10x the size or something ridiculous like that, if it links to deps that few/no other tests also link.
