### ISSUE TITLE
Requirements listing is incomplete

### ISSUE THREAD

**Issue by rajbos** [actions/runner#2664]
**Describe the bug**
The documentation in this repository does not mention the full list of prerequisites for the runner service. It only lists .NET core in the list for each platform (and some libs for Linux). I expect a minimum of `node` and `git` is needed, with some minimal version installed of each. Please add that to the repo

**To Reproduce**
Follow the pre-req links in the README to for example [Start - Linux](https://github.com/actions/runner/blob/main/docs/start/envlinux.md)

**Expected behavior**
Mentioning the minimally installed software to execute the service

## Runner Version and Platform
Not relevant / Latest

OS of the machine running the runner? ALL

**Comment by nikola-jokic** [comment]
Hi @rajbos,

The list of requirements you are mentioning are dependent on your intentions. The runner does not need to have git installed in order to run.
If you look at the `actions/actions-runner`, it does not have git. Node is included in runner externals so the list is complete.

It is the same for docker. You don't need docker installed if you are not running docker action for example

**Comment by rajbos** [comment]
So to check, as long as I do not intent to checkout code, I can still host a runner without having Git installed then?

**Comment by nikola-jokic** [comment]
Yes ☺️ 
I tested it to be sure by running the latest version of the runner image, check that git is not on the system, register it to the repo and execute the checkout
