### ISSUE TITLE
Daily action was not triggered

### ISSUE THREAD

**Issue by Saluev** [actions/runner#2673]
**Describe the bug**
I have a [Github action in my private repository](https://github.com/stry-inc/api/actions/workflows/daily_report.yml) which is configured to be run daily:
```
on:
  schedule:
    - cron: '00 08 * * *'
```

And it wasn't triggered today, although it was working like clockwork for previous half an year.
<img width="555" alt="Screenshot 2023-06-26 at 19 36 11" src="https://github.com/actions/runner/assets/2435301/6d03fb73-89ea-4a88-af7d-b8c8125eca4b">

**To Reproduce**
I don't know how it can be reproduced, looks like a bug in the scheduler. [Another daily action](https://github.com/stry-inc/api/actions/workflows/backup.yml) was triggered successfully. 

**Expected behavior**
I expect cron jobs to be run every day.

## Runner Version and Platform
Irrelevant.

## What's not working?
Cron as action trigger.

## Job Log Output
No job — no output.

## Runner and Worker's Diagnostic Logs
No job — no logs.

**Comment by nikola-jokic** [comment]
Hey @Saluev,

Thank you for submitting this issue. However, this problem is not related to the runner itself, it affects the platform overall. Can you please redirect this issue to the [GitHub Community Support Forum](https://github.com/orgs/community/discussions/categories/actions-and-packages)?

Since this is not related to the runner, I will close this issue :relaxed:
