### ISSUE TITLE
brew update is failing on the macos-12-xl

### ISSUE THREAD

**Issue by grzegorzkrukowski** [actions/runner#2677]
**Describe the bug**

`brew update` is failing on the macos-12-xl runners.

**To Reproduce**
1. run `brew update` on the macos-12-xl runner
2. See the error saying: 
```
remote: fatal: object d86be3efada113da47edac78e11d3fb7009ccb2c cannot be read        
remote: aborting due to possible repository corruption on the remote side.
```

It is working fine on normal `macos-12` which is 12.6.7.

**Expected behavior**
`brew update` should run successfully

## Runner Version and Platform
macOS 12.6.6
Image: macos-12
  Version: 20230623.2
  Included Software: https://github.com/actions/runner-images/blob/macOS-12/20230623.2/images/macos/macos-12-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macOS-12%2F20230623.2

## What's not working?
<img width="944" alt="CleanShot 2023-07-03 at 12 22 34@2x" src="https://github.com/actions/runner/assets/1301068/2332e2cb-8ef9-46d8-a3aa-a525df0ba7e2">

## Job Log Output
```
Run brew update
  brew update
  shell: /bin/bash -e {0}
remote: fatal: object a81badabcd6 cannot be read        
remote: aborting due to possible repository corruption on the remote side.
fatal: protocol error: bad pack header
Error: Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask failed!
```

**Comment by mr-cal** [comment]
I've been seeing the same failure on `macos-12` runners starting 28-Jun-2023.

https://github.com/canonical/craft-providers/actions/runs/5447794442/jobs/9910223037?pr=347#step:2:6

```
  brew update
  brew install multipass
  shell: /bin/bash -e {0}
remote: fatal: object 901201bdfa15c90a44cac56da65f31670153c728 cannot be read        
remote: aborting due to possible repository corruption on the remote side.
```

**Comment by jonathanecooke90** [comment]
Same problem on MacOS 13.4.1. Been experiencing since July 2nd. 

`remote: fatal: object 901201bdfa15c90a44cac56da65f31670153c728 cannot be read
remote: aborting due to possible repository corruption on the remote side.
fatal: protocol error: bad pack header
Error: Fetching /opt/homebrew/Library/Taps/homebrew/homebrew-cask failed!
Updated 1 tap (homebrew/cask).`

**Comment by mr-cal** [comment]
Related: https://github.com/Homebrew/brew/issues/15621

**Comment by nikola-jokic** [comment]
Hey @grzegorzkrukowski,

Can you please redirect this issue to the [runner-images](https://github.com/actions/runner/issues/2677) repository? This issue is not related to the runner itself, it affects the environment in which the runner is executed. Submitting the issue there would ensure the correct team sees it :relaxed: 

I will close this issue here since it is not related to the runner, but please, do submit the issue to the runner-images repository.
