### ISSUE TITLE
Double-quoted strings in an expression does not throw any visible errors

### ISSUE THREAD

**Issue by ebarzilay-godaddy** [actions/runner#2689]
This is a problem with GH actions, though I'm not sure that it is a runner issue or a UI issue.

On an enterprise account (with self-hosted runners, but same problem with GH runners) I had finally realized that a specific PR action was not firing because I used double-quotes in an env `${{ ... }}` expression.  I now see that [this is documented](https://docs.github.com/en/actions/learn-github-actions/expressions#literals) so I fixed it, but the problem is that previously the action would just not run, with no indication of the error anyway, including when viewing the action.

The expected behavior --- as documented in the above page --- is that some error is thrown, so I expect to see it somewhere (the action page showing an error, or the action running should show it).  Instead, I had nothing...

## Runner Version and Platform

Current one (fails when using GH runners too), using ubuntu.

## What's not working?

No indication of the error anywhere I checked.

## Job Log Output

The failed action is not shown, so no logs.

**Comment by nikola-jokic** [comment]
Hey @ebarzilay-godaddy,

Thank you for taking the time to submit the issue! This issue is not related to the runner itself, it concerns the GitHub actions platform more generally. Could you please post your feedback on the [GitHub Community Support Forum](https://github.com/orgs/community/discussions/categories/actions?discussions_q=is%3Aopen+category%3AActions). Using the forum ensures that we route your problem to the correct team. :relaxed: 

Since we try to keep issues related to the runner itself, I will close this issue.
