### ISSUE TITLE
Wrong output when comparing Repository variable and enviroment variable

### ISSUE THREAD

**Issue by prabhat2k15** [actions/runner#2698]
**Describe the bug**
I have two variables in Gihub actions. One is repository variable in vars.QUARTER = Q3 and env.Q=Q3. The equality comparison of both give wrong output(Snapshot attached)

**To Reproduce**
Run this script
``` 
 - name: docker push equal
       env:  
        Q: "Q$(date '+%q')"
        Q2: "${{ vars.QUARTER }}"
#       if:  ${{ env.QUARTER == env.Q }}
       run: |
        echo "env.Q: ${{ env.Q }}"
        echo "vars.QUARTER: ${{ vars.QUARTER }}"
        echo "env.Q2: ${{ env.Q2 }}"
        echo "vars.QUARTER != env.Q: ${{ vars.QUARTER != env.Q}}"
        echo "contains( vars.QUARTER, env.Q): ${{ contains( vars.QUARTER, env.Q) }}"
        echo "env.Q2 == env.Q: ${{ env.Q2==env.Q }}"
```
**Expected behavior**
${{ vars.QUARTER != env.Q}} should give false but giving true

## Runner Version and Platform
runs-on: ubuntu-latest

OS of the machine running the runner? OSX/Windows/Linux/...
Linux

## What's not working?
Please include error messages and screenshots.
<img width="525" alt="Screenshot 2023-07-15 at 8 29 34 AM" src="https://github.com/actions/runner/assets/26509407/721dfeaf-9fe8-4fb4-b4f6-7e9b6a13e024">

**Comment by nikola-jokic** [comment]
Hey @prabhat2k15,

The env you have specified as `Q: "Q$(date '+%q')"` is not evaluated as a shell script during the template evaluation. The `run` content will be written as a script file and executed by the shell, so it will seem like the `env.Q` value is `Q3` in this case. The reason they are not equal is because they are compared as literals. So the exact comparison here would be `Q$(date '+%q') == Q3` which is false, or as your script showed, `vars.Quarter` is not equal to the `env.Q`.
Environment variables are not evaluated as a shell script expression. They can be constant, or they can be template expressions. 

I will close this issue now, it may be handy for your use-case to use step to evaluate the quarter, and then reference it:
```yaml
steps:
    - name: evaluate Q
      id: eval_q
      run: echo "Q=Q$(date '+%q')" >> $GITHUB_OUTPUT
    - name: guarded_step
      if: ${{ steps.eval_q.outputs.Q == vars.QUARTER }}
      ...
```
