### ISSUE TITLE
Required Workflows don't receive the `pull_request.closed` or `pull_request_target.closed` events anymore

### ISSUE THREAD

**Issue by ajmalab** [actions/runner#2737]
**Describe the bug**
Hello, after updating the runner to 2.307.1,  `closed` type events aren't received by `required_workflows` anymore. The issue seems to be only affecting required_workflows, repo specific GHA still receive the `closed` events. 

**To Reproduce**
1. Create a required workflow for an org with a `pull_request.closed` trigger.
2. Enable the required workflow on a test repo in the org
3. Create and close/merge a PR to the test repo

**Expected behavior**
The required workflow should be triggered

## Runner Version and Platform
2.307.1

OS of the machine running the runner? ubuntu-latest

## What's not working?
The required workflow is not triggered

**Comment by nikola-jokic** [comment]
Hey @ajmalab,

Thank you for submitting this issue! This issue does not seem to be related to the runner. It affects the platform more generally. Can you please redirect it to the [GitHub Community Support Forum](https://github.com/orgs/community/discussions/categories/actions)? It is actively monitored and using it will ensure that the correct team sees it.

Since we try to keep issues related to the runner here, I will close this issue now. But please, redirect it to the Community Support Forum :relaxed:
