### ISSUE TITLE
Chrome is missing from windows-latest registry (Software\Clients\StartMenuInternet)

### ISSUE THREAD

**Issue by roniemartinez** [actions/runner#2829]
**Describe the bug**
Google Chrome is missing from `Software\Clients\StartMenuInternet` for `windows-latest`

**To Reproduce**
https://github.com/roniemartinez/browsers/pull/95

**Expected behavior**
Tests should pass

## Runner Version and Platform
windows-latest

## What's not working?
Google Chrome should be registered in `Software\Clients\StartMenuInternet`

## Job Log Output
If applicable, include the relevant part of the job / step log output here.  All sensitive information should already be masked out, but please double-check before pasting here.

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by nikola-jokic** [comment]
Hey @roniemartinez,

This issue is related to the software running on the machine in which the runner executes. Can you please redirect this issue to the [runner-images repository](https://github.com/actions/runner-images)? I will close this issue here since it is not related to the runner itself. :relaxed:
