### ISSUE TITLE
Runner logs infrastructure details

### ISSUE THREAD

**Issue by bryanmacfarlane** [actions/runner#283]
**Describe the bug**
consider this log output:
```bash
Run actions/setup-ruby@v1
##[error]Version 2.6.3 not found
##[error]Node run failed with exit code 1
```
The fact that the action is run with node and the return code protocol is not relevant to the user.  the user workflow did not run node - they are setting up ruby.  the `failure` is that 2.6.3 is not found, that's it.  The second line should go to trace / _diag

**To Reproduce**
See setup ruby example above.

**Expected behavior**
The return code of the handler execution should not go to user logs.

## Runner Version and Platform
2.163.1

**Comment by bryanmacfarlane** [comment]
fyi @TingluoHuang

**Comment by philipengberg** [comment]
Experiencing the same since last night

**Comment by dakale** [comment]
Would it be useful to just update the error to something like: `Action has exited with code N` instead? With no error at all it relies on the action itself printing a ##error so sometimes users wont get any message at all depending on the action. We pass/fail the step based on the exit code so that contract is still in place. Could the toolkit expose an exit function that prints and message and exits the process with eg 1? That way people arent left to fend for themselves and have a consistent contract with the actions runner

`run:` steps also print "##[error]Process completed with exit code 1.", should we consider removing that too? There may be a better way to get consistency across various step types here

**Comment by bryanmacfarlane** [comment]
> Would it be useful to just update the error to something like: Action has exited with code N instead?

The return code is an internal protocol so.

> With no error at all it relies on the action itself printing a ##error so sometimes users wont get any message at all depending on the action.

All the actions and examples so try, catch, error with a message.  If a message isn't outputted the step will still fail and there won't be an error annotation which is what the action chose to do by not outputting a message.  This will also encourage actions to output a useful message.

> run: steps also print "##[error]Process completed with exit code 1.", should we consider removing that too? 

No, in that case the **_user_** ran something and we're outputting the result of what they ran.

**Comment by dakale** [comment]
Thought about it more, and I agree now. Small PR here https://github.com/actions/runner/pull/290
