### ISSUE TITLE
image size reduction, why does a ubuntu image ship alpine node?

### ISSUE THREAD

**Issue by raffis** [actions/runner#2863]
**Describe the bug**
Why does the runner image which is based on ubuntu ship node built for alpine?
This is ~200M unnecessary bloat as far as I see, /home/runner/externals/_*alpine.

**Expected behavior**
Don't include alpine binaries. size reduction by ~200M.

## Runner Version and Platform
ghcr.io/actions/actions-runner:2.308.0

**Comment by nikola-jokic** [comment]
Hey @raffis,

The reason is that if you are running a container action that is based on the alpine, we need to provide a node for that alpine container :relaxed:. That is why the runner always ships with the alpine node, not because it needs it to run correctly, but because the action that may land on the runner may need the alpine node.
