### ISSUE TITLE
`x32` ABI support is failing

### ISSUE THREAD

**Issue by Cyan4973** [actions/runner#2888]
**Describe the bug**

Since a few days, all CI tests involving `x32` binaries (compiled with `-mx32` flag) are failing at execution time.
Compilation works fine, but trying to run the produced binaries fails.
This happen with recent versions of Ubuntu os, pinned or unpinned.

**To Reproduce**
Compile with `-mx32` flag, run the produced binary.

**Expected behavior**
All these `x32` binaries used to work correctly.

## Platform
OS of the machine running the runner: Linux Ubuntu 22.04, latest.

Ubuntu 20.04 still works

**Comment by nikola-jokic** [comment]
Hey @Cyan4973,

It seems like this issue is related to the underlying machine, and not the runner itself. Can you please submit this issue to the [runner-images repository](https://github.com/actions/runner-images/issues/new/choose)? I will close this issue here since it is not related to the runner itself :relaxed:
