### ISSUE TITLE
Running on local repository

### ISSUE THREAD

**Issue by bukowa** [actions/runner#301]
Hello, how can i trigger a workflow on a local repository (not pushing changes) and get a report?

**Comment by ericsciple** [comment]
[repository dispatch](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#external-events-repository_dispatch) can be used to trigger a run

**Comment by bryanmacfarlane** [comment]
answered

**Comment by aabeling** [comment]
I don't understand how this helps to run a workflow on a local repository.
Can someone please describe a complete setup and example to achieve this?

As far as I understood the repository_dispatch is just another trigger for starting a workflow. But it will still use the workflow code from the remote repository on github.

I came across this issue because I am searching for a way to test workflows before pushing them to the github repository.
I know of https://github.com/nektos/act but this does seem to not work for self hosted runners.
