### ISSUE TITLE
BUG: Any value assigned to GITHUB_ACTIONS_RUNNER_TRACE enforces Verbose logging

### ISSUE THREAD

**Issue by booleanbetrayal** [actions/runner#3045]
It appears that assigning any value to `GITHUB_ACTIONS_RUNNER_TRACE` will always force `TraceLevel.Verbose` logging, which seems misleading / unexpected. Instead, this environment variable should accept and assign (with appropriate validation) a value reflective of the `TraceLevel` enum.

https://github.com/actions/runner/blob/9e3e57ff90c089641a3a5833c2211841da1a37f8/src/Runner.Common/TraceSetting.cs#L11-L22

**Comment by fhammerl** [comment]
Hi @booleanbetrayal, just a drive-by comment from a non-codeowner as I got pinged on this due to my closed PR above: not sure if this will get categorised as a bug - `GITHUB_ACTIONS_RUNNER_TRACE` is more of a 'bool shouldTrace' boolean from the looks of it, not a 'TraceEnum traceLevel'.

I'd recommend reframing it as a Feature Request **specific to the runner application**.
The [GitHub Community Support Forum](https://github.com/orgs/community/discussions/categories/actions) might be a good place to bring up these sort of discussions as well.
