### ISSUE TITLE
Can we register a runner without the runner dist via the API / REST

### ISSUE THREAD

**Issue by npalm** [actions/runner#558]
We are hosting our own self hosted runners, which scales up and down. To avoid builds are failing we always have an offline runner registered. We register this runner manaually. The offline runners are required after deployment of [our solution](https://040code.github.io/2020/05/25/scaling-selfhosted-action-runners) and each 60 days since GitHub removes offline runners after 60 days. We would like to automate the creating of our offline runners. It would be very handy if we can register a runnr by invoking several API calls via REST for example. Is there any docs, scripts or example available how to do this? Our setup is available as [Terraform module](https://github.com/philips-labs/terraform-aws-github-runner)

**Comment by TingluoHuang** [comment]
we don't have any doc around this since the registration includes an RSA public/private key exchange, and you have to prepare all the config files that runner required right, otherwise, the runner won't start after the config.

However, if you really want, you can reverse engineering everything by `export GITHUB_ACTIONS_RUNNER_HTTPTRACE=1` then run `./config.sh`, it will printout all the HTTP request the runner makes during config to the logs file under `_diag` folder.

Make that's a starting point?

**Comment by npalm** [comment]
@TingluoHuang  thanks, yes it give some good pointers to get started.

**Comment by miked63017** [comment]
@npalm did you make any progress on this? I am going to start doing some debug builds to try to figure out this same thing, but hoping maybe someone solved this already.

**Comment by npalm** [comment]
@miked63017 thanks for the note, no we did not have the time yet. I have linked our issue.

**Comment by miked63017** [comment]
@npalm thanks!
