### ISSUE TITLE
Support team managed groups of repos

### ISSUE THREAD

**Issue by halberom** [actions/runner#621]
**Describe the enhancement**
Allow runners to be associated with a group of repositories, owned and managed by a team.

In organisations which maintain separate cloud accounts per team, the proposed [self-hosted runner groups](https://github.com/github/roadmap/issues/73) in the github plan is not ideal, as it requires enterprise admins to manage the runners+groups relationship.   In reality, this team likely has absolutely nothing to do with day to day management of team repos, cloud accounts or the runners the teams are using.

**How would it work?**
A new Actions tab would be added to Team settings.  In which the team admins can create groups of repos (from the team repos), and add runners to them.

**Additional information**
This goes beyond just the runner, as it would also require API and UI enhancements.

**Comment by nikola-jokic** [comment]
Hey @halberom,

Because this enhancement is not really related to the runner, but the platform more generally, can you please post your feedback on the [GitHub Community Support Forum](https://github.community/c/code-to-cloud/52)? This page is actively monitored, and using that forum will ensure that your enhancement is routed to the correct team.

Likely, this change if accepted would not require changes on the runner itself, so I will close this issue for now. We will re-open this issue if this enhancement requires changes to the runner in the future.

Thank you :relaxed:
