### ISSUE TITLE
Request to set default values for inputs as environment variables.

### ISSUE THREAD

**Issue by shivammathur** [actions/runner#732]
**Describe the enhancement**
Set default values for inputs as environment variables.

**Code Snippet**
If I have this in my `actions.yml`, the runner can set up something like `abc-input-default` with the value `x.y.z`
```yml
abc-input:
  default: 'x.y.z'
```

**Additional information**
This will help in accessing default values for inputs with a single lookup without having to hardcode values or parse `actions.yml`.

**Comment by plocket** [comment]
From my understanding of syntax it would be more like
```yml
author:
    default: '$GITHUB_ACTOR'
```
I might be wrong because I can't find the syntax for accessing default github action env variables.

Question for the team - would there be access to values other than [default environment variables](https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#default-environment-variables) at that point, or would those be the only ones developers could use?

**Comment by plocket** [comment]
Why was this issue closed?
