### ISSUE TITLE
Run fails with "  GitHub Actions has encountered an internal error when running your job." with no other output

### ISSUE THREAD

**Issue by gliptak** [actions/runner#744]
Link to the run https://github.com/lambci/docker-lambda/actions/runs/292197960

https://github.com/lambci/docker-lambda/pull/312

**Comment by mcpengelly** [comment]
whats going on here? I have this as well

**Comment by maartenvn** [comment]
I have the same issue

**Comment by VinceDPM** [comment]
Also seeing this error.

**Comment by trallnag** [comment]
Just happened to me as well https://github.com/trallnag/prometheus-fastapi-instrumentator/actions/runs/318289967

**Comment by alanhamlett** [comment]
Same here.

**Comment by Javieratapiab** [comment]
Same issue

**Comment by jonas-schievink** [comment]
This is now causing several Rust CI runs to fail:

* https://github.com/rust-lang-ci/rust/actions/runs/336037245
* https://github.com/rust-lang-ci/rust/actions/runs/336351650

**Comment by Atarity** [comment]
Same issue. CI just finished 1st job successfully then didn't start 2nd job. Run stopped by timeout with "GitHub Actions has encountered an internal error when running your job". I've tried re-run previous successful runs and the result is the same that means it doesn't relate to changed code.

**Comment by gliptak** [comment]
https://www.githubstatus.com/history doesn't indicate any Actions outages

**Comment by ruvceskistefan** [comment]
Hi everyone,
Are you still seeing this issue? If so, could you please provide us with diag logs, so that we can understand the cause of the problem.

**Comment by ruvceskistefan** [comment]
I'm going to close out this issue until we hear back from you, please let us know if you are still seeing this issue!

**Comment by highb** [comment]
I encountered this issue when I was using `fromJson()` inside of an `if` that was referencing an empty output. Correcting the output to have proper JSON content fixed it for me. That being said, this error could be caused by any number of weird edge cases that the GH runners aren't prepared to handle so YMMV. 😅 

On a related note, it would be great if the GHA YAML parser pre-parsed the file for any invalid references in interpolated statements so that if I referenced something nonsensical like `${{ steps.banana.ootpoot.what }}` it would tell me I've lost it. 😄
