### ISSUE TITLE
Reliability of long-running SSH workflow steps

### ISSUE THREAD

**Issue by derekm** [actions/runner#793]
**Describe the bug**
Something about the NAT traversal or default gateways on Actions VMs requires modifying SSH daemon settings on remote targets in order for long-running commands to succeed.

Without applying the sshd settings as in this stackoverflow: https://stackoverflow.com/questions/39229912/ssh-connection-fails-to-disconnect
long-running tasks on remote machines don't provide console output and don't disconnect properly when commands have completed.

**To Reproduce**
Before applying the above settings, tasks would fail after about 2 hours and 13 minutes (see "Running e2e"): https://github.com/pravega/pravega-operator/runs/1349103378?check_suite_focus=true
even though the tasks only last about 30-40 minutes.

After applying the above settings, stdout is received and the task completes after about 30 minutes (see "Running e2e"):
https://github.com/pravega/pravega-operator/runs/1360094533?check_suite_focus=true

**Expected behavior**
I expect network traffic to function reliably on default settings.

The workflow step began working after applying TCPKeepAlive settings on the remote SSH daemon as seen here:
https://github.com/pravega/pravega-operator/pull/454/files#diff-dbfb6d3f5ffe33d97f58d348d8998f8b84a0c974df84ab5f5900e0fdce047d85R2

**Comment by nikola-jokic** [comment]
Hi @derekm,

This issue does not seem to be related to the runner repository, but to the host system on which it operates. Since your solution was related to the host system only (ssh in this case), I am closing this issue because we try to keep issues here related to this repository. Thank you for submitting it anyway! But if you feel like it is a runner issue, please let us know 😊
