### ISSUE TITLE
No RepositoryName available through env vars

### ISSUE THREAD

**Issue by matkoch** [actions/runner#833]
I only have access to the full repository identifier or the owner... No the single repository name.

<img width="358" alt="image" src="https://user-images.githubusercontent.com/5005566/100522319-12877280-31aa-11eb-8f90-44336a4d2bd3.png">

**Comment by igagis** [comment]
This might be related to #826

**Comment by matkoch** [comment]
Is this really such a hard thing to do that it remains open for half a year? /cc @TingluoHuang

I'll add, I'm also missing the `WORKFLOW_ID`... Not having this requires an additional roundtrip to the rest client that could be avoided.

**Comment by matkoch** [comment]
@chrispat any chance to get this pushed ?

**Comment by nikola-jokic** [comment]
Hey @matkoch,

Can you please post this feedback to the [GitHub Community Support Forum](https://github.com/orgs/community/discussions/categories/actions-and-packages)? Like noted in the comment, this enhancement does not affect only the runner, and using this forum can really help increase visibility to this feature, and prioritize it for future enhancements.

We are trying to keep issues related to the runner here, and since this will not affect the runner, I will close it now.

**Comment by sixcorners** [comment]
```
$ GITHUB_REPOSITORY=nuke-build/nuke
$ echo "${GITHUB_REPOSITORY##*/}"
nuke
```
