### ISSUE TITLE
Workflows should be able to dynamically provision new runners

### ISSUE THREAD

**Issue by dimisjim** [actions/runner#881]
**Describe the enhancement**
Workflows being able to dynamically provision new runners using AWS (or any other cloud) APIs to provision new virtual machines or docker containers. 

So instead of having to have a predefined pool of runners, in which the workflows can run their jobs in, it would be great for them to be able to run their runners according to the demand at hand. They would, based on a predefined template (be it a virtual machine image (i.e AWS AMI) or a Dockerfile), provision an ephemeral runner, and then destroy it when the job is done, just like it is done in the GH-hosted runners.

Somewhat similar to https://github.com/actions/runner/issues/395.

**Comment by dimisjim** [comment]
Basically instead of having this requirement that @davidkarlsen is mentioning here: https://github.com/actions/runner/issues/395#issuecomment-731554812 (that a workflow needs to point to a preexisting runner label), the workflow should be able to generate this label by itself.

**Comment by dskvr** [comment]
I've done this before and it doesn't really require any changes to github actions to make it work. There's several ways to achieve this, but the way I set it up was as an ephemeral runner:

1. Have a lambda triggered by webhook or a cheap instance that polls api for jobs in a queue (I ended up going with instance because lambda had some edge cases) 
2. Spawn an instance who's init script programmatically sets up a new github runner based on the enqueued-job's label (for example: linux) 
3. Once that instance is setup, it will appear as a runner in github, and assume the job in the queue.
4. Self-destruct the instance upon completion 

I unfortunately do not have the time to write an article, but I did borrow some ideas from the following article: 
1. https://dev.to/wayofthepie/ephemeral-self-hosted-github-actions-runners-1h5m

That said, it would be nice if Github Actions was a bit more accommodating to this requirement

**Comment by dimisjim** [comment]
@dskvr Indeed, this is what I ended up implementing.

But like you said, it would be nice if this behavior was built-in gh-actions

**Comment by kkmann** [comment]
Second, would be nice to simply connect your account to aws/azure/gcs pick an instance size and go!

**Comment by TingluoHuang** [comment]
This is not scoped to the runner repository, please submit feature request via https://github.community/c/code-to-cloud/github-actions/41
