### ISSUE TITLE
Fail Instead of Warn for Unknown Properties

### ISSUE THREAD

**Issue by danielhelfand** [actions/runner#933]
**Describe the bug**

I originally opened this [issue](https://github.com/actions/stale/issues/286) in actions/stale as this is the action I used when first experiencing this, but think it belongs here instead. 

When unknown properties are included as part of an action, there is only a warning message that displays that `Unexpected input` has been provided (#429). Since the action does not fail, users can miss this information for some time. It can also lead to the action being executed in an unintended way. It would be helpful if there was an option to fail if unknown properties are included.

**To Reproduce**
1. Use [actions/stale](https://github.com/actions/stale)
2. Include an unknown property
3. When it runs, see that the warning is displayed but the action still runs.

**Expected behavior**

The action should not run if unexpected input is provided or there should be a way to configure a failure if unexpected input is provided.

## Job Log Output

https://github.com/vmware-tanzu/carvel-kbld/actions/runs/497411016

**Comment by hross** [comment]
We will probably not change the behavior as it is today. I understand the desire for this but we don't provide support at this moment and I don't think this feature will gain more traction than other priorities in the next 6 months.

**Comment by danielhelfand** [comment]
@hross I understand that it's not a high priority item, but I do not see that as a reason to close this issue. I think it should at least be kept open so it could eventually be further considered.

**Comment by tristan957** [comment]
@hross could you provide a use-case for when someone would rather have a warning instead of an error in this situation? I cannot think of a single one. If your pipeline doesn't do what you expect it to do, why would that not be an error?

**Comment by eli-schwartz** [comment]
Cross-ref #514 where people actually complain that they cannot stand warnings at all. The actual issue there is that they have workflows which accept unbounded dynamic inputs, so the "expected use" of those workflows results in warnings.

Apparently this causes permanent yellow builds, which... conveniently are not shown anywhere and do not produce notifications, so it's not even clear why this matters...

So the problem here is twofold:
- in cases where the warning is correct, users *need* a hard failure, warnings are useless, they just lead to silently broken builds
- in cases where the warning is incorrect, users *need* to completely suppress warnings, because fake warnings that aren't correct lead to a culture of ignoring warnings.

No one is happy with the current state of affairs, but most people don't actually realize github even tries to check this.

Pretending everything is fine, then closing the ticket because "this feature isn't important to us" is a really bad state of affairs, and the biggest reason it is so terrible is because ***this is a bug report*** so please do not claim it is a feature, not a bug. :)

**Comment by eli-schwartz** [comment]
The logical solution to my mind is that actions themselves know whether they process dynamic properties, so it should be an attribute of the action itself, whether to completely suppress warnings or make them hard errors.

- It should not require every *user* of an action to configure their workflow files in order to opt in to verifying that their workflows are actually correct.
- It should not require every other user of an action to configure their workflow files in order to opt out of verifying that their dynamic inputs aren't a bug.


For actions that don't specify it one way or another, I guess for backwards compatibility make it a warning and preserve the status quo?
