### ISSUE TITLE
Run local workflow support

### ISSUE THREAD

**Issue by sd185233** [actions/runner#958]
When developing workflows, especially when trying new stuff in workflows, it would be nice to have the ability to test the workflows locally first, instead of committing and running for every change.   There are tools to do this - I didn't manage to get any tool to work and also would be nice if this was supported natively.

Example use case - 
-Download github runner
-Develop workflow locally
-Trigger workflow on local machine - runner local_wf.yml --repo repo_url --event push

...or are there any other ways to do this?

**Comment by callum-tait-pbx** [comment]
https://github.com/nektos/act ?

**Comment by sd185233** [comment]
I tried it...downloaded it, added to path, then run act from a WF dir, selected medium image size then run act with events but nothing appeared to happen.  I'll look into it again, but would be nice if this was something supported natively.

**Comment by rockandska** [comment]
A kind of `--anonymous` mode who will serve a http entrypoint allowing us to send a payload containing necessary information ( workflow.yaml, github.repository, etc..) would be nice to test a local directory workflow without having to add the self hosted runner to a remote repository.

**Comment by missedone** [comment]
2nd to this request, there were two critical incident on github actions recently https://www.githubstatus.com/history

we use github actions for daily CI/CD and production deployment, we're worried with the downtime of Github Actions impacts our product release.
so as fallback, better to be able to execute the github workflow from local laptop

**Comment by rockandska** [comment]
In fact, it seems it was here previously to https://github.com/actions/runner/pull/218, allowing users to start the runner against a local directory.

https://github.com/actions/runner/blob/8109c962f09d9acc473d92c595ff43afceddb347/src/Misc/layoutroot/run.sh#L20-L25

**Comment by JustinGrote** [comment]
`act` works well but it "emulates" the runner rather than using the actual code, so it will always be playing catch-up and not a true representation of the procses.

Agree with @rockandska where a  `Runner.Listener` flag to have it listen on a port for messages rather than phone home would allow tools to be developed to initiate "test" actions into the runner itself, since the API is open source in this repository (thanks!)

**Comment by rockandska** [comment]
@TingluoHuang / @juliobbv : any chances to see this feature back ?

Regards,

**Comment by hross** [comment]
We don't have plans to support this locally right now. Possibly in the future, but not in a 6 month time frame. I am going to close this and provide feedback but we would track a feature like this internally and not in the runner repo.

**Comment by ChristopherHX** [comment]
I tried implementing something like this during last weeks, but it probably contains a lot of bugs.
Maybe someone still want to try my `Runner.Server` Project based on this repo, even if this is unofficial.
https://github.com/ChristopherHX/runner.server
It is able to transform webhooks to actions jobs for the runner.
However my implementation may misbehave and is incomplete, because of some missing official code for a server  and missing Tests.

**Comment by rockandska** [comment]
Thanks @ChristopherHX, seems really nice
